#ifndef NEWSCOASTER_CATALOG_H
#define NEWSCOASTER_CATALOG_H


/****************************************************************************/


/* This file was created automatically by CatComp.
 * Do NOT edit by hand!
 */


#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif

#ifdef CATCOMP_ARRAY
#undef CATCOMP_NUMBERS
#undef CATCOMP_STRINGS
#define CATCOMP_NUMBERS
#define CATCOMP_STRINGS
#endif

#ifdef CATCOMP_BLOCK
#undef CATCOMP_STRINGS
#define CATCOMP_STRINGS
#endif


/****************************************************************************/


#ifdef CATCOMP_NUMBERS

#define MSG_AUTHENTICATING 0
#define MSG_ERROR 1
#define MSG_OKAY 2
#define MSG_UNKNOWN_USER 3
#define MSG_INCORRECT_PASSWORD 4
#define MSG_IN 5
#define MSG_NO_TCP_STACK 6
#define MSG_DOWNLOADING_GROUP_LIST 7
#define MSG_CONNECTING_WITH_SERVER 8
#define MSG_CANNOT_CONNECT_WITH_SERVER 9
#define MSG_CONNECTED 10
#define MSG_CANNOT_USE_SERVER 11
#define MSG_CANNOT_OBTAIN_GROUPLIST 12
#define MSG_FOUND_GROUPS 13
#define MSG_DATE_OF_LAST_GROUPLIST_DOWNLOAD_NOT_AVAILABLE 14
#define MSG_DOWNLOADING_NEW_GROUPS 15
#define MSG_CANNOT_OBTAIN_NEW_GROUPS_LIST 16
#define MSG_FOUND_NEW_GROUPS 17
#define MSG_FOUND_NEW_GROUPS_2 18
#define MSG_GET_NEW_GROUPS 19
#define MSG_SENDING_NEWS 20
#define MSG_SENDING 21
#define MSG_CANNOT_POST_TO_SERVER 22
#define MSG_ERROR_2 23
#define MSG_POST_FAILED 24
#define MSG_DONE 25
#define MSG_ABORTED 26
#define MSG_CANNOT_OPEN_FILE 27
#define MSG_SENDING_EMAIL 28
#define MSG_CANNOT_CONNECT_WITH_SMTP 29
#define MSG_CANNOT_USE_SMTP 30
#define MSG_CANNOT_SEND_TO_SMTP 31
#define MSG_ERROR_FOR_RECIPIENT 32
#define MSG_EMAIL_FAILED 33
#define MSG_MOVING_TO_SENT 34
#define MSG_MOVING_TO_SENT_2 35
#define MSG_MESSAGE_KILLED 36
#define MSG_MESSAGE_KILLED_ADVERT 37
#define MSG_MESSAGE_KILLED_DUPLICATE 38
#define MSG_MESSAGE_KILLED_TOO_MANY_LINES 39
#define MSG_PRESCANNING_KILLFILE 40
#define MSG_FETCH_NEWS 41
#define MSG_CREATE_SOME_NEWSGROUPS 42
#define MSG_NO_NEWS_FOR_GROUP 43
#define MSG_DOWNLOAD 44
#define MSG_LAST_100_OR_ALL 45
#define MSG_OLD_NEWS_IN_GROUP 46
#define MSG_HOW_MANY_MESSAGES 47
#define MSG_DOWNLOADING 48
#define MSG_CONNECTING_FOR 49
#define MSG_DOWNLOADING_FROM 50
#define MSG_SCANNING 51
#define MSG_CANNOT_GET_GROUP_INFO 52
#define MSG_NO_NEW_NEWS_FOR 53
#define MSG_DOWNLOADING_ARTICLES 54
#define MSG_READING_MSGID_HISTORY 55
#define MSG_DOWNLOADING_2 56
#define MSG_DOWNLOADING_3 57
#define MSG_DOWNLOADING_4 58
#define MSG_BODY_NOT_FOUND 59
#define MSG_DOWNLOADNG_OF 60
#define MSG_DOWNLOADING_5 61
#define MSG_MESSAGE_IS_NO_LONGER_AVAILABLE 62
#define MSG_UNABLE_TO_OPEN_FILE 63
#define MSG_INDEX_ERROR 64
#define MSG_INDEX_OUT_OF_DATE 65
#define MSG_READING_INDEX 66
#define MSG_INDEX_FORMAT_CHANGED 67
#define MSG_WRITING_INDEX 68
#define MSG_NEW_INDEX_FORMAT 69
#define MSG_INVALID_INDEX 70
#define MSG_CANNOT_OPEN_INDEX 71
#define MSG_CANNOT_CREATE_INDEX 72
#define MENU_PROJECT 73
#define MENU_FETCH_NEWS 74
#define MENU_FETCH_THIS_GROUP 75
#define MENU_SEND_NEWS 76
#define MENU_FETCH_GROUP_LIST 77
#define MENU_FETCH_NEW_GROUPS 78
#define MENU_DISCONNECT_FROM_SERVER 79
#define MENU_ABOUT_NEWSCOASTER 80
#define MENU_ABOUT_MUI 81
#define MENU_SYSTEM_INFORMATION 82
#define MENU_ICONIFY 83
#define MENU_QUIT 84
#define MENU_NEWSGROUPS 85
#define MENU_NEW_NEWSGROUP 86
#define MENU_EDIT_NEWSGROUP 87
#define MENU_ADVANCED_SETTINGS 88
#define MENU_DELETE_NEWSGROUP 89
#define MENU_ARCHIVE_NEWSGROUP 90
#define MENU_GROUPS_MANAGER 91
#define MENU_VIEW 92
#define MENU_LIST 93
#define MENU_TREE 94
#define MENU_SORT_GROUPS 95
#define MENU_SEARCH_GROUPS 96
#define MENU_GROUP_STATISTICS 97
#define MENU_RESET_GROUP 98
#define MENU_RESET_ALL_GROUPS 99
#define MENU_UPDATE_GROUPS 100
#define MENU_UPDATE_INDEX 101
#define MENU_UPDATE_ALL_INDICES 102
#define MENU_IMPORT_MESSAGES 103
#define MENU_MESSAGES 104
#define MENU_VIEW_2 105
#define MENU_FLAT 106
#define MENU_THREADED 107
#define MENU_READ_MESSAGE 108
#define MENU_EDIT_MESSAGE 109
#define MENU_SUPERSEDE_MESSAGE 110
#define MENU_CANCEL_MESSAGE 111
#define MENU_DELETE_MESSAGE 112
#define MENU_UNDELETE_MESSAGE 113
#define MENU_EXPORT_MESSAGE 114
#define MENU_VIEW_HEADER 115
#define MENU_MOVE_MESSAGE 116
#define MENU_COPY_MESSAGE 117
#define MENU_ADD_TO_KILLFILE 118
#define MENU_EXPORT_ADDRESS 119
#define MENU_POST_NEW_MESSAGE 120
#define MENU_FOLLOWUP_MESSAGE 121
#define MENU_REPLY_VIA_MAIL 122
#define MENU_FOLLOWUP_AND_REPLY 123
#define MENU_PERMANENTLY_DELETE 124
#define MENU_SELECTED_MESSAGES 125
#define MENU_ALL_READ 126
#define MENU_ALL_ONLINE 127
#define MENU_ALL_DUPLICATES 128
#define MENU_ALL_IN_GROUP 129
#define MENU_ALL_MESSAGES 130
#define MENU_SELECT 131
#define MENU_ALL 132
#define MENU_NONE 133
#define MENU_TOGGLE 134
#define MENU_FROM_POSTER 135
#define MENU_THIS_SUBJECT 136
#define MENU_ALL_READ_2 137
#define MENU_ALL_UNREAD 138
#define MENU_MARK_AS 139
#define MENU_UNREAD 140
#define MENU_READ 141
#define MENU_HELD 142
#define MENU_QUEUED 143
#define MENU_NORMAL 144
#define MENU_IMPORTANT 145
#define MENU_CHANGE_DATE__TO_CURRENT 146
#define MENU_DOWNLOAD_BODY 147
#define MENU_JOIN_MESSAGES 148
#define MENU_PREFERENCES 149
#define MENU_PROGRAM_SETTINGS 150
#define MENU_KILLFILE 151
#define MENU_USERS 152
#define MENU_CHANGE_PASSWORD 153
#define MENU_MUI_SETTINGS 154
#define TBAR_READ 155
#define TBAR_READ_HELP 156
#define TBAR_EXPORT 157
#define TBAR_EXPORT_HELP 158
#define TBAR_MOVE 159
#define TBAR_MOVE_HELP 160
#define TBAR_COPY 161
#define TBAR_COPY_HELP 162
#define TBAR_DELETE 163
#define TBAR_DELETE_HELP 164
#define TBAR_KILL 165
#define TBAR_KILL_HELP 166
#define TBAR_POST 167
#define TBAR_POST_HELP 168
#define TBAR_FOLLOWUP 169
#define TBAR_FOLLOWUP_HELP 170
#define TBAR_EDIT 171
#define TBAR_EDIT_HELP 172
#define TBAR_FETCH 173
#define TBAR_FETCH_HELP 174
#define TBAR_SEND 175
#define TBAR_SEND_HELP 176
#define TBAR_SEARCH 177
#define TBAR_SEARCH_HELP 178
#define TBAR_SETTINGS 179
#define TBAR_SETTINGS_HELP 180
#define TBAR_KILLFILE 181
#define TBAR_KILLFILE_HELP 182
#define MSG_ACCOUNTS 183
#define MSG_SERVERS 184
#define MSG_WRITE 185
#define MSG_READ 186
#define MSG_LISTS 187
#define MSG_MIME 188
#define MSG_DATEFORMAT_1 189
#define MSG_DATEFORMAT_2 190
#define MSG_NONE 191
#define MSG_SIGNATURE_1 192
#define MSG_SIGNATURE_2 193
#define MSG_SIGNATURE_3 194
#define MSG_SIGNATURE_4 195
#define MSG_SIGNATURE_5 196
#define MSG_SIGNATURE_6 197
#define MSG_SIGNATURE_7 198
#define MSG_SIGNATURE_8 199
#define MSG_NONE_2 200
#define MSG_SELECTED 201
#define MSG_FULL 202
#define MSG_DONT_DISCARD_MESSAGES 203
#define MSG_DISCARD_AFTER_X_DAYS 204
#define MSG_OFFLINE_READING 205
#define MSG_ONLINE_READING 206
#define MSG_NEWSSERVER_1 207
#define MSG_NEWSSERVER_2 208
#define MSG_NEWSSERVER_3 209
#define MSG_NEWSSERVER_4 210
#define MSG_NEWSSERVER_5 211
#define MSG_NEWSSERVER_6 212
#define MSG_NEWSSERVER_7 213
#define MSG_NEWSSERVER_8 214
#define MSG_GMT_M12 215
#define MSG_GMT_M11 216
#define MSG_GMT_M10 217
#define MSG_GMT_M9 218
#define MSG_GMT_M8 219
#define MSG_GMT_M7 220
#define MSG_GMT_M6 221
#define MSG_GMT_M5 222
#define MSG_GMT_M4 223
#define MSG_GMT_M3 224
#define MSG_GMT_M2 225
#define MSG_GMT_M1 226
#define MSG_GMT 227
#define MSG_GMT_P1 228
#define MSG_GMT_P2 229
#define MSG_GMT_P3 230
#define MSG_GMT_P4 231
#define MSG_GMT_P5 232
#define MSG_GMT_P6 233
#define MSG_GMT_P7 234
#define MSG_GMT_P8 235
#define MSG_GMT_P9 236
#define MSG_GMT_P10 237
#define MSG_GMT_P11 238
#define MSG_GMT_P12 239
#define MSG_NEVER 240
#define MSG_ALWAYS 241
#define MSG_ONLY_FOLLOWED_UP 242
#define MSG_NEVER_EXPIRE 243
#define MSG_EXPIRE_X_DAYS_FROM_CREATION 244
#define MSG_EXPIRE_X_DAYS_FROM_USAGE 245
#define MSG_CONTAINS 246
#define MSG_DOES_NOT_CONTAIN 247
#define MSG_KILL 248
#define MSG_MARK_AS_IMPORTANT 249
#define MSG_UNLIMITED_MESSAGES_PER_DOWNLOAD 250
#define MSG_MAXIMUM_N_TO_DOWNLOAD 251
#define MSG_DOWNLOAD_MESSAGES_OF_ANY_LENGTH 252
#define MSG_SKIP_LONGER_THAN_N_LINES 253
#define MSG_FROM 254
#define MSG_NEWSGROUPS 255
#define MSG_SUBJECT 256
#define MSG_MESSAGEID 257
#define MSG_HEADER 258
#define MSG_MESSAGE_BODY 259
#define MSG_ENTIRE_MESSAGE 260
#define MSG_BY_PERSON 261
#define MSG_BY_SUBJECT 262
#define MSG_BY_X_NEWSREADER 263
#define MSG_MESSAGE_HELP 264
#define MSG_UNREAD_MESSAGE 265
#define MSG_HELD_MESSAGE 266
#define MSG_REPLIED_MESSAGE 267
#define MSG_BODY_NOT_DOWNLOADED 268
#define MSG_NO_MESSAGE_SELECTED 269
#define MSG_LAST_DOWNLOADED 270
#define MSG_GROUP_HELP 271
#define MSG_ONLINE_READING_2 272
#define MSG_OFFLINE_READING_2 273
#define MSG_USING 274
#define MSG_GROUP_SUBSCRIBED 275
#define MSG_NO_GROUP_SELECTED 276
#define MSG_ARCHIVING 277
#define MSG_ARCHIVING_2 278
#define MSG_CANNOT_OPEN_FILE_TO_WRITE 279
#define MSG_READING_TITLE 280
#define MSG_MIME_ATTACHMENT 281
#define MSG_UNKNOWN_ATTACHMENT 282
#define MSG_FOLDERS 283
#define MSG_UNKNOWN_GROUP 284
#define MSG_FOLDER_OUTGOING 285
#define MSG_FOLDER_SENT 286
#define MSG_FOLDER_DELETED 287
#define MSG_SCANNING_2 288
#define MSG_SCANNING_FOUND 289
#define MSG_SEVERE_ERROR 290
#define MSG_NOT_ENOUGH_RAM 291
#define MSG_SCANNING_3 292
#define MSG_DIRECTORY_TO_SCAN 293
#define LABEL_NEWSSERVER 294
#define LABEL_DEFAULT 295
#define LABEL_POST_WITH_THIS_SERVER 296
#define MSG_LOGIN 297
#define MSG_LOGIN_FAILED 298
#define MSG_STARTUP 299
#define MSG_CONTINUE_OR_QUIT 300
#define MSG_NEWS_DIRECTORY_DOES_NOT_EXIST 301
#define MSG_PROGDIR_CANNOT_BE_ACCESSED 302
#define MSG_NEWS_DIRECTORY_CANNOT_BE_ACCESSED 303
#define MSG_DEFAULT_FOLLOWUP 304
#define MSG_DEFAULT_FROM 305
#define MSG_CHARSET_ERROR 306
#define MSG_CONTINUE 307
#define MSG_CHARSET_CANNOT_BE_ACCESSED 308
#define MSG_SHUTTING_DOWN 309
#define MSG_CLOSING_SOCKETS 310
#define MSG_SAVING_PREFS 311
#define MSG_SAVING_KILLFILE 312
#define MSG_SAVING_SERVERS 313
#define MSG_FREEING_MEMORY 314
#define MSG_DELETING_FILES 315
#define MSG_READING_GROUP_LIST 316
#define MSG_READ_GROUPS 317
#define MSG_SORTING_LIST 318
#define MSG_FOUND_GROUPS_2 319
#define MSG_GROUP_MANAGER 320
#define MSG_GROUP_LIST_DOES_NOT_EXIST 321
#define MSG_NEW_GROUP_FOR_SERVER 322
#define MSG_GROUP_MANAGER_2 323
#define MSG_CANCEL 324
#define MSG_MOVE_TO_WHICH_GROUP 325
#define MSG_MOVE 326
#define MSG_COPY_TO_WHICH_GROUP 327
#define MSG_MOVING 328
#define MSG_COPYING 329
#define MSG_MOVE_MESSAGE 330
#define MSG_NO_MESSAGES_TO_MOVE 331
#define MSG_COPY_MESSAGE 332
#define MSG_NO_MESSAGES_TO_COPY 333
#define MSG_DELETE_MESSAGES 334
#define MSG_DELETE_OR_CANCEL 335
#define MSG_DELETE_NOT_SENT_ARE_YOU_SURE 336
#define MSG_DELETE_MESSAGES_ARE_YOU_SURE 337
#define MSG_DELETING 338
#define MSG_DELETE_MESSAGE 339
#define MSG_NO_MESSAGES_TO_DELETE 340
#define MSG_UNDELETE_MESSAGES 341
#define MSG_UNDELETE_OR_CANCEL 342
#define MSG_UNDELETE_ARE_YOU_SURE 343
#define MSG_UNDELETING 344
#define MSG_UNDELETE_MESSAGE 345
#define MSG_NO_MESSAGES_TO_UNDELETE 346
#define MSG_MESSAGES_FROM_THIS_AUTHOR 347
#define MSG_RESPONSE_TO_MESSAGE 348
#define MSG_ALL_WHITH_THE_SAME_SUBJECT 349
#define MSG_MESSAGES_FROM_SERVER 350
#define MSG_MESSAGES_FROM_POSTING_HOST 351
#define MSG_KILL_IN_ALL_GROUPS 352
#define MSG_KILL_IN_THIS_GROUP 353
#define MSG_EXPORT_ADDRESS_ARE_YOU_SURE 354
#define MSG_EXPORT_ADDRESS 355
#define MSG_YES_OR_CANCEL 356
#define MSG_CANNOT_ACCESS_YAM_ADDRESSBOOK 357
#define MSG_ONLY_ONE_NEWSCOASTER_COPY_ALLOWED 358
#define MSG_NOT_AVAILABLE 359
#define MSG_FUNCTION_NOT_AVAILABLE_WHEN_CONNECTED 360
#define MSG_PLEASE_SELECT_GROUP_FOLDER 361
#define MSG_DOWNLOAD_GROUP_LIST_ARE_YOU_SURE 362
#define MSG_GET_GROUP_LIST 363
#define MSG_GROUP_LIST_DOWNLOADED 364
#define MSG_GROUP_LIST 365
#define MSG_SYSTEM_INFORMATION 366
#define MSG_SYSTEM_INFORMATION_SAVED 367
#define MSG_QUIT_PROGRAM 368
#define MSG_QUIT_OR_CANCEL 369
#define MSG_QUIT_ARE_YOU_SURE 370
#define MSG_SAVE_MESSAGE 371
#define MSG_SAVE_DISCARD_OR_CANCEL 372
#define MSG_SAVE_CHANGES_ARE_YOU_SURE 373
#define MSG_EDIT_NEWSGROUP 374
#define MSG_PLEASE_SELECT_GROUP_TO_EDIT 375
#define MSG_PLEASE_FINISH_EDITING_GROUP 376
#define MSG_GROUP_ADVANCED_SETTINGS 377
#define MSG_PLEASE_SELECT_GROUP 378
#define MSG_DELETE_GROUP_ARE_YOU_SURE 379
#define MSG_YOU_MAY_NOT_DELETE_FOLDER 380
#define MSG_ARCHIVE_GROUP 381
#define MSG_FILE_TO_SAVE_ARCHIVE_AS 382
#define MSG_SORT_NEWSGROUP 383
#define MSG_SORT_OR_CANCEL 384
#define MSG_SORT_GROUP_ARE_YOU_SURE 385
#define MSG_RESET_ARTICLE_POINTER 386
#define MSG_RESET_OR_CANCEL 387
#define MSG_RESET_ARTICLE_POINTER_ARE_YOU_SURE 388
#define MSG_RESET_ARTICLE_POINTERS 389
#define MSG_RESET_ALL_POINTERS_ARE_YOU_SURE 390
#define MSG_OPEN_GROUP_MANAGER_ARE_YOU_SURE 391
#define MSG_UPDATE_OR_CANCEL 392
#define MSG_UPDATE_GROUP_LIST_ARE_YOU_SURE 393
#define MSG_UPDATE_GROUP_INDEX_ARE_YOU_SURE 394
#define MSG_UPDATE_INDICES 395
#define MSG_UPDATE_ALL_INDICES_ARE_YOU_SURE 396
#define MSG_PLEASE_SELECT_MESSAGE 397
#define MSG_EDIT_MESSAGE 398
#define MSG_MESSAGE_TO_EDIT_IS_SENT 399
#define MSG_YOU_CAN_EDIT_ONLY_YOUR_MESSAGES 400
#define MSG_YOU_MUST_SELECT_MESSAGE_TO_EDIT 401
#define MSG_SUPERSEDE_MESSAGE 402
#define MSG_YOU_CAN_SUPERSEDE_ONLY_SENT_MESSAGES 403
#define MSG_YOU_MUST_SELECT_MESSAGE_TO_SUPERSEDE 404
#define MSG_CANCEL_MESSAGE_OR_NOT 405
#define MSG_CANCEL_MESSAGE_ARE_YOU_SURE 406
#define MSG_CANCEL_MESSAGE_QUEUED 407
#define MSG_IMMEDIATE_DELETE_ARE_YOU_SURE 408
#define MSG_DELETE_READ_MESSAGES 409
#define MSG_IMMEDIATE_DELETE_READ_ARE_YOU_SURE 410
#define MSG_DELETE_HEADERS 411
#define MSG_REMOVE_HEADERS_ARE_YOU_SURE 412
#define MSG_DELETE_DUPLICATES 413
#define MSG_DELETE_DUPLICATES_ARE_YOU_SURE 414
#define MSG_IMMEDIATE_DELETE_ALL_ARE_YOU_SURE 415
#define MSG_IMMEDIATE_DELETE_ALL_GROUPS_ARE_YOU_SURE 416
#define MSG_SURE_OR_CANCEL 417
#define MSG_DELETE_ALL_GROUPS_LAST_CHANCE 418
#define MSG_NEWSCOASTER_COMPOSING_MESSAGE 419
#define MSG_VIEW_HEADERS 420
#define MSG_KILL_MESSAGE 421
#define MSG_PLEASE_FINISH_DOWNLOADING_FIRST 422
#define MSG_DOWNLOADING_MESSAGE 423
#define MSG_CANNOT_DOWNLOAD_WHILE_DOWNLOADING_OTHER_MESSAGES 424
#define MSG_DOWNLOADING_BODIES 425
#define MSG_DELETING_NOT_AVAILABLE_HEADERS 426
#define MSG_MARK_MESSAGE 427
#define MSG_ONLY_MESSAGES_IN_GROUPS_CAN_BE_MARKED_UNREAD 428
#define MSG_ONLY_MESSAGES_IN_GROUPS_CAN_BE_MARKED_READ 429
#define MSG_ONLY_MESSAGES_IN_OUTGOING_CAN_BE_MARKED_HELD 430
#define MSG_ONLY_MESSAGES_IN_OUTGOING_CAN_BE_MARKED_QUEUED 431
#define MSG_CHANGE_DATE 432
#define MSG_YOU_CAN_CHANGE_DATE_OF_NOT_SENT 433
#define MSG_IMPOSSIBLE_TO_CHANGE_SETTINGS_WHEN_EDITING_MESSAGE 434
#define MSG_DELETE_USER 435
#define MSG_UNABLE_TO_DELETE_CURRENT_USER 436
#define MSG_DELETE_USER_ARE_YOU_SURE 437
#define MSG_YES_OR_NO 438
#define MSG_USER_DELETED_DELETE_PREFS 439
#define MSG_NEW_USER 440
#define MSG_USER_NAME_TOO_SHORT 441
#define MSG_USER_NAME_EXISTS 442
#define MSG_NEWS_DIRECTORY_IN_USE 443
#define MSG_PASSWORD_TOO_SHORT 444
#define MSG_CANNOT_CREATE_FOLDER 445
#define MSG_ENTER_NEW_PASSWORD 446
#define MSG_CHANGE_PASSWORD 447
#define MSG_ERROR_3 448
#define MSG_CANNOT_CREATE_FOLDER_2 449
#define MSG_RESET_OR_NOT 450
#define MSG_SERVER_CHANGED_RESET_ARTICLE_POINTER 451
#define MSG_JOINED_MESSAGE 452
#define MSG_YOU_MUST_ENTER_EMAIL_ADDRESS 453
#define MSG_BAD_LINE_LENGTH 454
#define MSG_ADD_SERVER 455
#define MSG_PLEASE_FINISH_EDITING_SERVER_BEFORE_ADDING_NEW 456
#define MSG_EDIT_SERVER 457
#define MSG_PLEASE_FINISH_EDITING_SERVER_BEFORE_EDITING_NEW 458
#define MSG_DEFAULT_SERVER_CHANGED_RESET_ALL_POINTERS 459
#define MSG_DELETE_SERVER 460
#define MSG_DELETE_SERVER_ARE_YOU_SURE 461
#define MSG_SERVER_DELETED_RESET_ARTICLE_POINTERS 462
#define MSG_CANNOT_DELETE_SERVER_BEING_EDITED 463
#define MSG_CANNOT_DELETE_LAST_SERVER 464
#define MSG_SERVER_ADDRESS_CHANGED_RESET_POINTERS 465
#define MSG_SELECT_FILE_TO_READ 466
#define MSG_DELETE_KILL_ENTRY 467
#define MSG_DELETE_KILL_ENTRY_ARE_YOU_SURE 468
#define MSG_SAVE_KILLFILE 469
#define MSG_GROUP_NOT_FOUND 470
#define MSG_SEARCH_GROUPS 471
#define MSG_PLEASE_SELECT_SOME_GROUPS 472
#define MSG_SEARCHING 473
#define MSG_SEARCHING_2 474
#define MSG_STATISTICS 475
#define MSG_UNKNOWN 476
#define MSG_CLIPBOARD_EMPTY 477
#define MSG_NO_TEXT_IN_CLIP 478
#define MSG_NO_AREA_MARKED 479
#define MSG_NOTHING_TO_REDO 480
#define MSG_NOTHING_TO_UNDO 481
#define MSG_NO_MEMORY_FOR_UNDO 482
#define MSG_NO_BOOKMARK_INSTALLED 483
#define MSG_BOOKMARK_LOST 484
#define MSG_GROUP 485
#define MSG_MSGS 486
#define MSG_SUB 487
#define MSG_ONLINE 488
#define MSG_SUBJECT_BOLD 489
#define MSG_DATE 490
#define MSG_NEWSGROUPS_BOLD 491
#define MSG_FROM_BOLD 492
#define MSG_SIZE 493
#define MSG_LINES 494
#define MSG_VALUE 495
#define MSG_FREQUENCY 496
#define MSG_NAME 497
#define MSG_NEWS_DIRECTORY 498
#define MSG_PASSWORD_PROTECTED 499
#define MSG_SUPERVISOR 500
#define MSG_FILENAME 501
#define MSG_MIME_TYPE 502
#define MSG_VIEWER 503
#define MSG_INDEFINATELY 504
#define MSG_DAYS_SINCE_CREATION 505
#define MSG_DAYS_SINCE_LAST_USED 506
#define MSG_DOES_NOT_CONTAIN_2 507
#define MSG_UNKOWN_2 508
#define MSG_HEADER_BOLD 509
#define MSG_TEXT 510
#define MSG_GROUPS 511
#define MSG_MATCH 512
#define MSG_ACTION 513
#define MSG_SKIP_REST 514
#define MSG_CREATION 515
#define MSG_LAST_USED 516
#define MSG_TIME_LIMIT 517
#define MSG_Y 518
#define MSG_N 519
#define MSG_SERVER_BOLD 520
#define MSG_PORT 521
#define MSG_USERNAME 522
#define MSG_AUTHENCICATION 523
#define MSG_DEFAULT 524
#define MSG_POSTING 525
#define MSG_IMPORTING_FOLDER 526
#define MSG_SEE_GUIDE_FOR_MORE_INFO 527
#define MSG_AUTHORS 528
#define MSG_FAILED_TO_CREATE_EDITOR_MCC 529
#define MSG_ABOUTTEXT 530
#define MSG_NEWSREADER 531
#define MSG_NEW_NEWSGROUP 532
#define LABEL_NEWSGROUP_NAME 533
#define LABEL_DESCRIPTION 534
#define LABEL_DEFAULT_SIG 535
#define LABEL_SUBSCRIBE 536
#define MSG_CANCEL_2 537
#define MSG_LAST_DOWNLOAD_DATE 538
#define MSG_FOLDER_LOCATION 539
#define MSG_APPROVED_HEADER 540
#define MSG_ALTERNATIVE_NAME 541
#define MSG_ALTERNATIVE_EMAIL 542
#define MSG_JOIN_MESSAGES 543
#define LABEL_SUBJECT 544
#define MSG_JOIN 545
#define LABEL_YOUR_NAME 546
#define LABEL_EMAIL_FOR_POSTING 547
#define LABEL_REAL_EMAIL_FOR_POSTING 548
#define LABEL_ORGANISATION 549
#define LABEL_TIME_ZONE 550
#define LABEL_DATE_DISPLAY_FORMAT 551
#define LABEL_ADD_DST_ADJUSTMENT 552
#define LABEL_USE_LOCALE_PREFS 553
#define LABEL_ALWAYS_CHECK_FOR_DUPES 554
#define LABEL_DELETE_HEADER_IF_NO_BODY 555
#define LABEL_DONT_SHOW_FROM_SUBJ_WHEN_DL 556
#define LABEL_SWITCH_GROUPS_WHEN_DL 557
#define LABEL_DONT_CONFIRM_WHEN_DELETING 558
#define LABEL_ALWAYS_CONFIRM_ON_QUIT 559
#define LABEL_LOGGING_ENABLED 560
#define LABEL_DELETE_LOG_ON_STARTUP 561
#define MSG_NEW_SERVER 562
#define MSG_EDIT_SERVER_2 563
#define MSG_MAKE_DEFAULT 564
#define MSG_USE_FOR_POSTING 565
#define MSG_DELETE_SERVER_2 566
#define MSG_GET_GROUPS 567
#define MSG_GROUPS_MANAGER 568
#define LABEL_SMTP_SERVER 569
#define LABEL_FOLLOWUP_ATTRIBUTATION_LINE 570
#define LABEL_CHARSET 571
#define MSG_READ_FROM_FILE 572
#define LABEL_LINE_LENGTH 573
#define LABEL_AUTO_REWRAP 574
#define LABEL_USE_X_NO_ARCHIVE 575
#define LABEL_USE_SHORT_X_NEWSREADER 576
#define LABEL_SNIP_SIG 577
#define LABEL_MULTIPLE_VIEW_WINDOWS 578
#define LABEL_2ND_LEVEL_QUOTING 579
#define MSG_2ND_LEVEL_QUOTE 580
#define LABEL_COLOURED 581
#define MSG_COLOURED_TEXT 582
#define LABEL_FLAGS 583
#define LABEL_DATE 584
#define LABEL_FROM_NEWSGROUP 585
#define LABEL_SIZE 586
#define LABEL_N_OF_LINES 587
#define LABEL_MIME_TYPE 588
#define LABEL_VIEWER 589
#define MSG_PLEASE_SELECT_VIEWER 590
#define LABEL_DEFAULT_VIEWER 591
#define MSG_NEW 592
#define MSG_SERVER 593
#define LABEL_NNTP_SERVER 594
#define LABEL_PORT 595
#define LABEL_USE_NNTP_AUTH 596
#define LABEL_USER 597
#define LABEL_PASSWORD 598
#define LABEL_KILLFILE_SETTINGS 599
#define LABEL_IF_HEADER 600
#define LABEL_IN_THE_GROUPS 601
#define LABEL_THEN 602
#define LABEL_SKIP_REST 603
#define MSG_ADD_REPLACE 604
#define MSG_DUPLICATE 605
#define LABEL_ADVERT_KILLFILE 606
#define LABEL_FIND 607
#define MSG_SUBSCRIBE 608
#define MSG_DOWLOAD_GROUP_LIST 609
#define LABEL_SEARCH_IN 610
#define LABEL_SEARCH_FOR 611
#define LABEL_CASE_SENSITIVE 612
#define MSG_START_SEARCH 613
#define LABEL_TYPE 614
#define MSG_START 615
#define MSG_SAVE 616
#define MSG_DISPLAY 617
#define MSG_CREATE_NEW_USER_DESCRIPTION 618
#define LABEL_USER_NAME 619
#define LABEL_PASSWORD_2 620
#define LABEL_NEWS_DIRECTORY 621
#define MSG_SELECT_DIRECTORY_TO_STORE_NEWS 622
#define LABEL_SUPERVISOR 623
#define LABEL_USE_PASSWORD 624
#define MSG_COPY_PREFS 625
#define MSG_USERS 626
#define MSG_ADD_NEW_USER 627
#define MSG_DELETE_USER_2 628
#define MSG_USER_LOGIN 629
#define MSG_PLEASE_ENTER_NEW_PASSWORD 630
#define MSG_ABOUT 631
#define MSG_FAILED_TO_CREATE_APPLICATION 632
#define MSG_CREATE_GROUP_HELP 633
#define MSG_CANCEL_CREATE_GROUP_HELP 634
#define MSG_GROUP_NAME_HELP 635
#define MSG_GROUP_DESCRIPTION_HELP 636
#define MSG_DEFAULT_SIGNATURE_HELP 637
#define MSG_MAXIMUM_MESSAGES_TO_DOWNLOAD_HELP 638
#define MSG_MAXIMUM_LINES_TO_DOWNLOAD_HELP 639
#define MSG_OFFLINE_VIEWING_HELP 640
#define MSG_ONLY_SUBSCRIBED_GROUPS_WILL_BE_DOWNLOADED_HELP 641
#define MSG_UPDATE_GROUP_HELP 642
#define MSG_CANCEL_UPDATE_GROUP_HELP 643
#define MSG_GROUP_NAME_TO_SUBSCRIBE_HELP 644
#define MSG_LAST_DOWNLOAD_HELP 645
#define MSG_KEEP_CHANGES_HELP 646
#define MSG_CANCEL_CHANGES_HELP 647
#define MSG_YOUR_NAME_HELP 648
#define MSG_YOUR_EMAIL_HELP 649
#define MSG_YOUR_REAL_EMAIL_HELP 650
#define MSG_ORGANISATION_HELP 651
#define MSG_SERVER_ADDRESS_HELP 652
#define MSG_PORT_HELP 653
#define MSG_POSTING_SERVER_HELP 654
#define MSG_SMTP_SERVER_HELP 655
#define MSG_SMTP_DOMAIN_HELP 656
#define MSG_FOLLOWUP_TEXT_HELP 657
#define MSG_SELECT_CHARSET_HELP 658
#define MSG_SET_TIME_ZONE_HELP 659
#define MSG_USE_LOCALE_HELP 660
#define MSG_DST_HELP 661
#define MSG_DATE_FORMAT_HELP 662
#define MSG_WRITE_LOG_HELP 663
#define MSG_DELETE_LOG_HELP 664
#define MSG_SWITCH_GROUP_HELP 665
#define MSG_MODE_HELP 666
#define MSG_CONFIRM_QUIT_HELP 667
#define MSG_SHOW_FROM_HELP 668
#define MSG_CONFIRM_DELETE_HELP 669
#define MSG_DUPE_CHECK_HELP 670
#define MSG_X_NO_ARCHIVE_HELP 671
#define MSG_SHORT_X_NEWSREADER_HELP 672
#define MSG_SELECT_SIGNATURE_HELP 673
#define MSG_GET_SIGNATURE_FROM_FILE_HELP 674
#define MSG_TYPE_SIGNATURE_HERE_HELP 675
#define MSG_LINE_LENGTH_HELP 676
#define MSG_AUTO_REWRAP_HELP 677
#define MSG_STRIP_SIGNATURE_HELP 678
#define MSG_DISPLAY_FLAGS_HELP 679
#define MSG_DISPLAY_FROM_HELP 680
#define MSG_DISPLAY_DATE_HELP 681
#define MSG_DISPLAY_SUBJECT_HELP 682
#define MSG_DISPLAY_SIZE_HELP 683
#define MSG_DISPLAY_LINES 684
#define MSG_ADD_KILFILE_HELP 685
#define MSG_NEW_KILLFILE_HELP 686
#define MSG_DELETE_KILLFILE_HELP 687
#define MSG_DUPLICATE_KILLFILE_HELP 688
#define MSG_KILL_HEADER_HELP 689
#define MSG_KILL_TEXT_HELP 690
#define MSG_KILL_GROUP_HELP 691
#define MSG_KILLFILE_EXPIRE_HELP 692
#define MSG_DAYS_LAST_FOR_HELP 693
#define MSG_WHAT_TO_DO_IF_MATCHED_HELP 694
#define MSG_SORT_OF_MATCH_HELP 695
#define MSG_WHAT_TO_DO_IF_KILLFILE_MATCHED_HELP 696
#define MSG_CHECK_REST_HELP 697
#define MSG_ADVERT_KILLFILE 698
#define MSG_OPEN_NEW_VIEW_WINDOW_HELP 699
#define MSG_SELECT_MIME_TYPE_HELP 700
#define MSG_SELECT_VIEWER_HELP 701
#define MSG_SELECT_DEFAULT_VIEWER_HELP 702
#define MSG_CREATE_NEW_MIME_TYPE_HELP 703
#define MSG_DELETE_MIME_TYPE_HELP 704
#define MSG_NEW_FOLDER_HELP 705
#define MSG_DOWNLOAD_GROUP_LIST_HELP 706
#define MSG_SEARCH_GROUP_HELP 707
#define MSG_SEARCH_HEADER_HELP 708
#define MSG_SEARCH_STRING_HELP 709
#define MSG_CASE_SENSITIVE_SEARCH_HELP 710
#define MSG_STATISTICS_CRITERIA_HELP 711
#define MSG_ADD_THIS_USER_HELP 712
#define MSG_DO_NOT_ADD_USER 713
#define MSG_USERNAME_HELP 714
#define MSG_PASSWORD_HELP 715
#define MSG_PASSWORD_PROTECTION_HELP 716
#define MSG_NEWS_DIRECTORY_HELP 717
#define MSG_SUPERVISOR_HELP 718
#define MSG_COPY_PREFS_HELP 719
#define MSG_ADD_USER_HELP 720
#define MSG_DELETE_USER_HELP 721
#define MSG_ENTER_USERNAME_HELP 722
#define MSG_ENTER_PASSWORD_HELP 723
#define MSG_NEW_PASSWORD_HELP 724
#define MSG_CHANGE_PASSWORD_HELP 725
#define MSG_CANCEL_CHANGES_2_HELP 726
#define MSG_COUNT_DIFFERS_FROM_ENTRIES 727
#define MSG_CANNOT_ALLOCATE_FIB 728
#define MSG_WARNING 729
#define MSG_OLD_PREFS_FILE 730
#define MSG_ABORT 731
#define MSG_EMAIL_FORMAT 732
#define MSG_PLAIN_TEXT 733
#define MSG_ATACHMENT_CORRUPTED 734
#define MSG_YDECODED_ATTACH 735
#define MSG_FOLLOWUP_REPLY 736
#define MSG_FOLLOWUP_REPLY_OR_CANCEL 737
#define MSG_FOLLOWUP_OR_REPLY 738
#define MSG_FIND 739
#define MSG_NO_MORE_OCCURANCES 740
#define MSG_NO_OCCURANCES_FOUND 741
#define MSG_HEADERS 742
#define MSG_PLAIN_TEXT_SECTION 743
#define MSG_HTML_SECTION 744
#define MSG_SAVE_NEWS_ITEM_AS 745
#define MSG_ENCODING 746
#define MSG_LENGTH 747
#define MENU_MESSAGE 748
#define MENU_FOLLOWUP_REPLY 749
#define MENU_EXPORT 750
#define MENU_ADD_TO_KILLFILE_2 751
#define MENU_EXPORT_ADDRESS_2 752
#define MENU_MARK_AS_2 753
#define MENU_NORMAL_2 754
#define MENU_IMPORTANT_2 755
#define MENU_TOGGLE_HEADERS 756
#define MENU_PREVIOUS_IN_THREAD 757
#define MENU_PREVIOUS 758
#define MENU_NEXT 759
#define MENU_DELETE_THEN_NEXT 760
#define MENU_CLOSE_WINDOS 761
#define MENU_EDIT 762
#define MENU_FIND_IN_MESSAGE 763
#define MENU_FIND_NEXT 764
#define MSG_COPY 765
#define MENU_ROT13_DECODE 766
#define MENU_ATTACHMENTS 767
#define MENU_VIEW_ATTACHMENT 768
#define MENU_SAVE_ATTACHMENT 769
#define MSG_VIEW 770
#define MSG_ATTACHMENTS_LIST_HELP 771
#define MSG_VIEW_ATTACHMENT_HELP 772
#define MSG_SAVE_ATTACHMENT_HELP 773
#define MSG_FOLLOWUP_REPLY_2 774
#define MSG_ADD_TO_KILLFILE 775
#define MSG_PREVIOUS_MESSAGE 776
#define MSG_PREVIOUS_IN_THREAD 777
#define MSG_DELETE_NEXT 778
#define MSG_NEXT_MESSAGE 779
#define MSG_FIND_TEXT 780
#define LABEL_FIND_2 781
#define LABEL_CASE_SENSITIVE_2 782
#define MSG_FIND_2 783
#define MSG_ADD_TO_KILLFILE_HELP 784
#define MSG_PREVIOUS_HELP 785
#define MSG_PREVIOUS_IN_THREAD_HELP 786
#define MSG_DELETE_NEXT_HELP 787
#define MSG_NEXT_HELP 788
#define MSG_FOLLOWUP_REPLY_HELP 789
#define MSG_EXPORT_HELP 790
#define MSG_EMAIL_STYLE_HELP 791
#define MSG_TEXT_TO_SEARCH_HELP 792
#define MSG_FIND_NEXT_HELP 793
#define MSG_EXPORT 794
#define MSG_VIEW_PART 795
#define MSG_SAVE_PART 796
#define MSG_VIEW_UUE 797
#define MSG_SAVE_UUE 798
#define MSG_MESSAGE 799
#define MSG_ATTACHMENTS 800
#define MSG_OPTIONS 801
#define MSG_PLEASE_SELECT_NEWSGROUP 802
#define MSG_ADD_REMOVE_GROUP 803
#define MSG_DISCARD_OR_CANCEL 804
#define MSG_DISCARD_CHANGES_ARE_YOU_SURE 805
#define MSG_SELECT_FILE_TO_ATTACH 806
#define LABEL_NEWSGROUPS 807
#define LABEL_TO 808
#define MSG_ADD_ATTACHMENT 809
#define MSG_DELETE_ATTACHMENT 810
#define LABEL_FROM 811
#define LABEL_FOLLOWUP_TO 812
#define MSG_SEND_TO_QUEUE 813
#define MSG_POSTPONE 814
#define MSG_ROT13 815
#define MSG_READ_FROM_FILE_2 816
#define MSG_SEND_HELP 817
#define MSG_ADD_OR_REMOVE_GROUP_TO_POST_HELP 818
#define MSG_ADD_OR_REMOVE_GROUP_TO_FOLLOWUP_TO_HELP 819
#define MSG_QUEUE_HELP 820
#define MSG_HOLD_HELP 821
#define MSG_CANCEL_MESSAGE_HELP 822
#define MSG_INSERT_TEXT_FROM_FILE_HELP 823
#define MSG_SELECT_SIGNATURE_FOR_MESSAGE_HELP 824
#define MSG_TO_HELP 825
#define MSG_NEWSGROUP_HELP 826
#define MSG_SUBJECT_HELP 827
#define MSG_FROM_HELP 828
#define MSG_FOLLOWUP_TO_HELP 829
#define MSG_WRITE_MESSAGE 830
#define MSG_EDIT_OR_CONTINUE 831
#define MSG_NO_SUBJECT 832
#define MSG_EMPTY_MESSAGE 833
#define MSG_ALL_QUOTED 834
#define MSG_NO_RAM_FOR_ATTACHMENTS 835
#define MSG_CANNOT_FIND_FILE_TO_ATTACH 836
#define MSG_NEWSCOASTER_EDITING_MESSAGE 837
#define MSG_NO_RAM_TO_READ_MESSAGE 838
#define MSG_OLD_MESSAGE 839
#define MSG_REPLYING_TO_AN_OLD_POST 840
#define MSG_FOLLOWUP_OR_REPLY_2 841
#define MSG_EMAIL_REPLY_REQUESTED 842
#define MSG_YOU_MUST_SELECT_MESSAGE_TO_REPLY 843
#define MENU_MESSAGE_2 844
#define MSG_SAVE_2 845
#define MSG_RECV_FAILED_EBADF 846
#define MSG_RECV_FAILED_ENOTCONN 847
#define MSG_RECV_FAILED_EWOULDBLOCK 848
#define MSG_RECV_FAILED_EINTR 849
#define MSG_RECV_FAILED_UNKNOWN 850
#define MSG_POSTER 851
#define LABEL_SUBJECT_2 852
#define MSG_DUPLICATING_FILE 853
#define MSG_RENAME_OVERWRITE_OR_CANCEL 854
#define MSG_FILE_ALREADY_EXISTS 855

#endif /* CATCOMP_NUMBERS */


/****************************************************************************/


#ifdef CATCOMP_STRINGS

#define MSG_AUTHENTICATING_STR "Authenticating..\n"
#define MSG_ERROR_STR "Error!"
#define MSG_OKAY_STR "_Okay"
#define MSG_UNKNOWN_USER_STR "\033cAuthentication Failed - Unknown User"
#define MSG_INCORRECT_PASSWORD_STR "\033cAuthentication Failed - Incorrect Password"
#define MSG_IN_STR "In!\n"
#define MSG_NO_TCP_STACK_STR "\033cPlease start a\nTCP stack!"
#define MSG_DOWNLOADING_GROUP_LIST_STR "Downloading Group List"
#define MSG_CONNECTING_WITH_SERVER_STR "Connecting with '%s'...\n"
#define MSG_CANNOT_CONNECT_WITH_SERVER_STR "\033cCannot connect with Newsserver!"
#define MSG_CONNECTED_STR "Connected!\n"
#define MSG_CANNOT_USE_SERVER_STR "\033cCannot use this Newsserver!\nError: %s"
#define MSG_CANNOT_OBTAIN_GROUPLIST_STR "\033cCannot Obtain GroupList!\nError: %s"
#define MSG_FOUND_GROUPS_STR "Found %d Groups...\n"
#define MSG_DATE_OF_LAST_GROUPLIST_DOWNLOAD_NOT_AVAILABLE_STR "\033cDate of last newsgroupslist download not available!\nPlease try 'Fetch Group List' first.\n"
#define MSG_DOWNLOADING_NEW_GROUPS_STR "Downloading New Newsgroups.."
#define MSG_CANNOT_OBTAIN_NEW_GROUPS_LIST_STR "\033cCannot Obtain New NewsGroups List!\nError: %s"
#define MSG_FOUND_NEW_GROUPS_STR "Found %d New Groups...\n"
#define MSG_FOUND_NEW_GROUPS_2_STR "\033cFound %d New Groups!\n"
#define MSG_GET_NEW_GROUPS_STR "Get New Groups"
#define MSG_SENDING_NEWS_STR "Sending News.."
#define MSG_SENDING_STR "Sending: %s\n"
#define MSG_CANNOT_POST_TO_SERVER_STR "\033cCannot post to this Newsserver!"
#define MSG_ERROR_2_STR "Error: %s"
#define MSG_POST_FAILED_STR "Error - Post Failed!"
#define MSG_DONE_STR "Done\n"
#define MSG_ABORTED_STR "Aborted!\n"
#define MSG_CANNOT_OPEN_FILE_STR "Cannot open file:\n  %s"
#define MSG_SENDING_EMAIL_STR "Sending Email.."
#define MSG_CANNOT_CONNECT_WITH_SMTP_STR "\033cCannot connect with SMTP server!"
#define MSG_CANNOT_USE_SMTP_STR "\033cCannot use this SMTP server!\nError: %s"
#define MSG_CANNOT_SEND_TO_SMTP_STR "\033cCannot send to this SMTP server!\nError: %s"
#define MSG_ERROR_FOR_RECIPIENT_STR "\033cError for recipient %s:\n%s"
#define MSG_EMAIL_FAILED_STR "Email Failed:\n%s"
#define MSG_MOVING_TO_SENT_STR "Moving to sent.."
#define MSG_MOVING_TO_SENT_2_STR "Moving %d to sent..\n"
#define MSG_MESSAGE_KILLED_STR "Message %d Killed! (%s match)\n"
#define MSG_MESSAGE_KILLED_ADVERT_STR "Message %d Killed! ('Advert')\n"
#define MSG_MESSAGE_KILLED_DUPLICATE_STR "Message %d Killed! (Duplicate Message)\n"
#define MSG_MESSAGE_KILLED_TOO_MANY_LINES_STR "Message %d Killed! (Too Many Lines)\n"
#define MSG_PRESCANNING_KILLFILE_STR "Pre-Scanning Killfile ( %d / %d )\n"
#define MSG_FETCH_NEWS_STR "Fetch News"
#define MSG_CREATE_SOME_NEWSGROUPS_STR "\033cPlease create some newsgroups first.\n(Select \"New Newsgroup\" from the Newsgroups menu.)"
#define MSG_NO_NEWS_FOR_GROUP_STR "\033cYou have not yet downloaded news for\n%s\nDo you wish to fetch all available messages,\nor only the last 100 messages?"
#define MSG_DOWNLOAD_STR "Download"
#define MSG_LAST_100_OR_ALL_STR "_Last 100 Messages|_All Messages"
#define MSG_OLD_NEWS_IN_GROUP_STR "\033cYou have not yet downloaded news for\n%s\nDo you wish to fetch the last %d messages,\nor only the last 100 messages?"
#define MSG_HOW_MANY_MESSAGES_STR "_Last 100 Messages|L_ast %d Messages"
#define MSG_DOWNLOADING_STR "Downloading.."
#define MSG_CONNECTING_FOR_STR "Connecting for %s..."
#define MSG_DOWNLOADING_FROM_STR "Downloading %s from %s"
#define MSG_SCANNING_STR "Scanning: %s\n"
#define MSG_CANNOT_GET_GROUP_INFO_STR "\033cCannot get Group information from this Newsserver\nError: %s"
#define MSG_NO_NEW_NEWS_FOR_STR "No new news for %s!\n"
#define MSG_DOWNLOADING_ARTICLES_STR "Downloading Articles: %d to %d\n"
#define MSG_READING_MSGID_HISTORY_STR "Reading in messageID history...\n"
#define MSG_DOWNLOADING_2_STR "Downloading (1/%d) %s\n"
#define MSG_DOWNLOADING_3_STR "Downloading (%d/%d) %s\n"
#define MSG_DOWNLOADING_4_STR "Downloading (%d/%d) %s\n%s - %s"
#define MSG_BODY_NOT_FOUND_STR "BODY not found\n"
#define MSG_DOWNLOADNG_OF_STR "Downloading %d of %d..\n"
#define MSG_DOWNLOADING_5_STR "Downloading...\n"
#define MSG_MESSAGE_IS_NO_LONGER_AVAILABLE_STR "This message is no longer available!\n"
#define MSG_UNABLE_TO_OPEN_FILE_STR "\033cUnable to open file:\n%s"
#define MSG_INDEX_ERROR_STR "Index Error"
#define MSG_INDEX_OUT_OF_DATE_STR "Out of date index file format!\nPlease select 'Update Index' from the\nNewsgroups menu"
#define MSG_READING_INDEX_STR "Reading Index"
#define MSG_INDEX_FORMAT_CHANGED_STR "Index Format Changed - Please wait.."
#define MSG_WRITING_INDEX_STR "Writing Index.."
#define MSG_NEW_INDEX_FORMAT_STR "New Index Format - Updating.."
#define MSG_INVALID_INDEX_STR "Error - Not a valid index file!\n"
#define MSG_CANNOT_OPEN_INDEX_STR "Couldn't open index file!"
#define MSG_CANNOT_CREATE_INDEX_STR "Couldn't create new index file!"
#define MENU_PROJECT_STR "Project"
#define MENU_FETCH_NEWS_STR "Fetch News"
#define MENU_FETCH_THIS_GROUP_STR "Fetch News for this Group"
#define MENU_SEND_NEWS_STR "Send News"
#define MENU_FETCH_GROUP_LIST_STR "Fetch Group List"
#define MENU_FETCH_NEW_GROUPS_STR "Fetch New Groups"
#define MENU_DISCONNECT_FROM_SERVER_STR "Disconnect From Newsserver"
#define MENU_ABOUT_NEWSCOASTER_STR "About NewsCoaster..."
#define MENU_ABOUT_MUI_STR "About MUI..."
#define MENU_SYSTEM_INFORMATION_STR "System Information..."
#define MENU_ICONIFY_STR "Iconify"
#define MENU_QUIT_STR "Quit"
#define MENU_NEWSGROUPS_STR "Newsgroups"
#define MENU_NEW_NEWSGROUP_STR "New Newsgroup..."
#define MENU_EDIT_NEWSGROUP_STR "Edit Newsgroup..."
#define MENU_ADVANCED_SETTINGS_STR "Advanced Settings..."
#define MENU_DELETE_NEWSGROUP_STR "Delete Newsgroup"
#define MENU_ARCHIVE_NEWSGROUP_STR "Archive Newsgroup..."
#define MENU_GROUPS_MANAGER_STR "Groups Manager..."
#define MENU_VIEW_STR "View"
#define MENU_LIST_STR "List"
#define MENU_TREE_STR "Tree"
#define MENU_SORT_GROUPS_STR "Sort Groups"
#define MENU_SEARCH_GROUPS_STR "Search Groups..."
#define MENU_GROUP_STATISTICS_STR "Group Statistics..."
#define MENU_RESET_GROUP_STR "Reset Group Article Pointer "
#define MENU_RESET_ALL_GROUPS_STR "Reset All Groups' Pointers "
#define MENU_UPDATE_GROUPS_STR "Update Groups"
#define MENU_UPDATE_INDEX_STR "Update Index"
#define MENU_UPDATE_ALL_INDICES_STR "Update All Indices"
#define MENU_IMPORT_MESSAGES_STR "Import Messages..."
#define MENU_MESSAGES_STR "Messages"
#define MENU_VIEW_2_STR "View"
#define MENU_FLAT_STR "Flat"
#define MENU_THREADED_STR "Threaded"
#define MENU_READ_MESSAGE_STR "Read Message"
#define MENU_EDIT_MESSAGE_STR "Edit Message..."
#define MENU_SUPERSEDE_MESSAGE_STR "Supersede Message..."
#define MENU_CANCEL_MESSAGE_STR "Cancel Message"
#define MENU_DELETE_MESSAGE_STR "Delete Message"
#define MENU_UNDELETE_MESSAGE_STR "Undelete Message"
#define MENU_EXPORT_MESSAGE_STR "Export Message"
#define MENU_VIEW_HEADER_STR "View Header"
#define MENU_MOVE_MESSAGE_STR "Move Message..."
#define MENU_COPY_MESSAGE_STR "Copy Message..."
#define MENU_ADD_TO_KILLFILE_STR "Add to Killfile..."
#define MENU_EXPORT_ADDRESS_STR "Export Address to YAM"
#define MENU_POST_NEW_MESSAGE_STR "Post New Message"
#define MENU_FOLLOWUP_MESSAGE_STR "Followup Message..."
#define MENU_REPLY_VIA_MAIL_STR "Reply via Email..."
#define MENU_FOLLOWUP_AND_REPLY_STR "Followup and Reply..."
#define MENU_PERMANENTLY_DELETE_STR "Permanently Delete"
#define MENU_SELECTED_MESSAGES_STR "Selected Messages"
#define MENU_ALL_READ_STR "All Read Messages"
#define MENU_ALL_ONLINE_STR "All Online Headers"
#define MENU_ALL_DUPLICATES_STR "All Duplicates"
#define MENU_ALL_IN_GROUP_STR "All in this Group"
#define MENU_ALL_MESSAGES_STR "ALL Messages"
#define MENU_SELECT_STR "Select"
#define MENU_ALL_STR "All"
#define MENU_NONE_STR "None"
#define MENU_TOGGLE_STR "Toggle"
#define MENU_FROM_POSTER_STR "All from this poster"
#define MENU_THIS_SUBJECT_STR "All with this subject"
#define MENU_ALL_READ_2_STR "All Read Messages"
#define MENU_ALL_UNREAD_STR "All Unread Messages"
#define MENU_MARK_AS_STR "Mark as"
#define MENU_UNREAD_STR "Unread"
#define MENU_READ_STR "Read"
#define MENU_HELD_STR "Held"
#define MENU_QUEUED_STR "Queued"
#define MENU_NORMAL_STR "Normal"
#define MENU_IMPORTANT_STR "Important"
#define MENU_CHANGE_DATE__TO_CURRENT_STR "Change Date To Current"
#define MENU_DOWNLOAD_BODY_STR "Download Body"
#define MENU_JOIN_MESSAGES_STR "Join Messages..."
#define MENU_PREFERENCES_STR "Preferences"
#define MENU_PROGRAM_SETTINGS_STR "Program Settings..."
#define MENU_KILLFILE_STR "KillFile..."
#define MENU_USERS_STR "Users..."
#define MENU_CHANGE_PASSWORD_STR "Change Password..."
#define MENU_MUI_SETTINGS_STR "MUI Settings..."
#define TBAR_READ_STR "_Read"
#define TBAR_READ_HELP_STR "Read the selected message"
#define TBAR_EXPORT_STR "E_xport"
#define TBAR_EXPORT_HELP_STR "View or Save parts of the\nselected message\n(attachments)"
#define TBAR_MOVE_STR "_Move"
#define TBAR_MOVE_HELP_STR "Move the selected message(s)\nto another folder"
#define TBAR_COPY_STR "_Copy"
#define TBAR_COPY_HELP_STR "Copy the selected message(s)\nto another folder"
#define TBAR_DELETE_STR "_Delete"
#define TBAR_DELETE_HELP_STR "Delete the selected\nmessage(s)"
#define TBAR_KILL_STR "_Kill"
#define TBAR_KILL_HELP_STR "Add a new killfile based on\nthe selected message"
#define TBAR_POST_STR "_Post"
#define TBAR_POST_HELP_STR "Post a new message"
#define TBAR_FOLLOWUP_STR "_Followup"
#define TBAR_FOLLOWUP_HELP_STR "Followup the selected\nmessage (to the newsgroup)"
#define TBAR_EDIT_STR "_Edit"
#define TBAR_EDIT_HELP_STR "Edit the selected message"
#define TBAR_FETCH_STR "Fetch"
#define TBAR_FETCH_HELP_STR "Fetch news"
#define TBAR_SEND_STR "Send"
#define TBAR_SEND_HELP_STR "Send news"
#define TBAR_SEARCH_STR "Search"
#define TBAR_SEARCH_HELP_STR "Search for a message"
#define TBAR_SETTINGS_STR "Settings"
#define TBAR_SETTINGS_HELP_STR "Program settings"
#define TBAR_KILLFILE_STR "Killfile"
#define TBAR_KILLFILE_HELP_STR "View and edit the killfile"
#define MSG_ACCOUNTS_STR "Accounts"
#define MSG_SERVERS_STR "Servers"
#define MSG_WRITE_STR "Write"
#define MSG_READ_STR "Read"
#define MSG_LISTS_STR "Lists"
#define MSG_MIME_STR "MIME"
#define MSG_DATEFORMAT_1_STR "DD-MMM-YY"
#define MSG_DATEFORMAT_2_STR "DD-MM-YY"
#define MSG_NONE_STR "None"
#define MSG_SIGNATURE_1_STR "Signature 1"
#define MSG_SIGNATURE_2_STR "Signature 2"
#define MSG_SIGNATURE_3_STR "Signature 3"
#define MSG_SIGNATURE_4_STR "Signature 4"
#define MSG_SIGNATURE_5_STR "Signature 5"
#define MSG_SIGNATURE_6_STR "Signature 6"
#define MSG_SIGNATURE_7_STR "Signature 7"
#define MSG_SIGNATURE_8_STR "Signature 8"
#define MSG_NONE_2_STR "None"
#define MSG_SELECTED_STR "Selected"
#define MSG_FULL_STR "Full"
#define MSG_DONT_DISCARD_MESSAGES_STR "Don't Discard Messages"
#define MSG_DISCARD_AFTER_X_DAYS_STR "Discard After x Days:"
#define MSG_OFFLINE_READING_STR "Offline Reading"
#define MSG_ONLINE_READING_STR "Online Reading"
#define MSG_NEWSSERVER_1_STR "Newsserver 1"
#define MSG_NEWSSERVER_2_STR "Newsserver 2"
#define MSG_NEWSSERVER_3_STR "Newsserver 3"
#define MSG_NEWSSERVER_4_STR "Newsserver 4"
#define MSG_NEWSSERVER_5_STR "Newsserver 5"
#define MSG_NEWSSERVER_6_STR "Newsserver 6"
#define MSG_NEWSSERVER_7_STR "Newsserver 7"
#define MSG_NEWSSERVER_8_STR "Newsserver 8"
#define MSG_GMT_M12_STR "GMT-12"
#define MSG_GMT_M11_STR "GMT-11"
#define MSG_GMT_M10_STR "GMT-10"
#define MSG_GMT_M9_STR "GMT-9"
#define MSG_GMT_M8_STR "GMT-8 (PDT)"
#define MSG_GMT_M7_STR "GMT-7 (MDT)"
#define MSG_GMT_M6_STR "GMT-6 (CMT)"
#define MSG_GMT_M5_STR "GMT-5 (EST)"
#define MSG_GMT_M4_STR "GMT-4 (ADT)"
#define MSG_GMT_M3_STR "GMT-3"
#define MSG_GMT_M2_STR "GMT-2"
#define MSG_GMT_M1_STR "GMT-1"
#define MSG_GMT_STR "GMT (GMT)"
#define MSG_GMT_P1_STR "GMT+1 (MET)"
#define MSG_GMT_P2_STR "GMT+2 (EET)"
#define MSG_GMT_P3_STR "GMT+3"
#define MSG_GMT_P4_STR "GMT+4"
#define MSG_GMT_P5_STR "GMT+5"
#define MSG_GMT_P6_STR "GMT+6"
#define MSG_GMT_P7_STR "GMT+7"
#define MSG_GMT_P8_STR "GMT+8 (PST)"
#define MSG_GMT_P9_STR "GMT+9"
#define MSG_GMT_P10_STR "GMT+10"
#define MSG_GMT_P11_STR "GMT+11"
#define MSG_GMT_P12_STR "GMT+12"
#define MSG_NEVER_STR "Never"
#define MSG_ALWAYS_STR "Always"
#define MSG_ONLY_FOLLOWED_UP_STR "Only if in followed up to post"
#define MSG_NEVER_EXPIRE_STR "Never Expire"
#define MSG_EXPIRE_X_DAYS_FROM_CREATION_STR "Expire x days from creation:"
#define MSG_EXPIRE_X_DAYS_FROM_USAGE_STR "Expire x days from last usage:"
#define MSG_CONTAINS_STR "Contains"
#define MSG_DOES_NOT_CONTAIN_STR "Does Not Contain"
#define MSG_KILL_STR "Kill"
#define MSG_MARK_AS_IMPORTANT_STR "Mark As Important"
#define MSG_UNLIMITED_MESSAGES_PER_DOWNLOAD_STR "Unlimited Messages per Download"
#define MSG_MAXIMUM_N_TO_DOWNLOAD_STR "Maximum # of Messages to Download:"
#define MSG_DOWNLOAD_MESSAGES_OF_ANY_LENGTH_STR "Download messages of any length"
#define MSG_SKIP_LONGER_THAN_N_LINES_STR "Skip messages longer than this # of lines:"
#define MSG_FROM_STR "From"
#define MSG_NEWSGROUPS_STR "Newsgroups"
#define MSG_SUBJECT_STR "Subject"
#define MSG_MESSAGEID_STR "MessageID"
#define MSG_HEADER_STR "Header"
#define MSG_MESSAGE_BODY_STR "Message Body"
#define MSG_ENTIRE_MESSAGE_STR "Entire Message"
#define MSG_BY_PERSON_STR "By Person"
#define MSG_BY_SUBJECT_STR "By Subject"
#define MSG_BY_X_NEWSREADER_STR "By X-Newsreader"
#define MSG_MESSAGE_HELP_STR "From: %s\nSubject: %s\nDate: %s %s\nNewsgroups: %s\nSize: %d\n# of Lines: %d\nFilename: %s%s%s%s%s\n"
#define MSG_UNREAD_MESSAGE_STR "\nUnread message"
#define MSG_HELD_MESSAGE_STR "\nMessage is Held"
#define MSG_REPLIED_MESSAGE_STR "\nYou have replied to this message"
#define MSG_BODY_NOT_DOWNLOADED_STR "\nBody not yet downloaded"
#define MSG_NO_MESSAGE_SELECTED_STR "No message selected"
#define MSG_LAST_DOWNLOADED_STR "\nLast Downloaded: "
#define MSG_GROUP_HELP_STR "%s\n# of Messages: %d\n# of Unread Messages: %d%s%s%s%s%s\nFolder Location: %s"
#define MSG_ONLINE_READING_2_STR "\nOnline Reading"
#define MSG_OFFLINE_READING_2_STR "\nOffline Reading"
#define MSG_USING_STR "\nUsing "
#define MSG_GROUP_SUBSCRIBED_STR "\nYou are Subscribed to this group."
#define MSG_NO_GROUP_SELECTED_STR "No group selected"
#define MSG_ARCHIVING_STR "Archiving.."
#define MSG_ARCHIVING_2_STR "Archiving.. (%d/%d)"
#define MSG_CANNOT_OPEN_FILE_TO_WRITE_STR "Couldn't open file %s to write to.\n"
#define MSG_READING_TITLE_STR "%s - Reading %s [%d messages - %d unread]"
#define MSG_MIME_ATTACHMENT_STR "MIME Attachment"
#define MSG_UNKNOWN_ATTACHMENT_STR "NewsCoaster is unable to determine\nthe file format of this attachment.\nPlease set it manually"
#define MSG_FOLDERS_STR "Folders"
#define MSG_UNKNOWN_GROUP_STR "Unknown (%d)"
#define MSG_FOLDER_OUTGOING_STR "\033o[10].outgoing"
#define MSG_FOLDER_SENT_STR "\033o[11].sent"
#define MSG_FOLDER_DELETED_STR "\033o[12].deleted"
#define MSG_SCANNING_2_STR "Scanning.."
#define MSG_SCANNING_FOUND_STR "Scanning: %s (found: "
#define MSG_SEVERE_ERROR_STR "Severe Error!"
#define MSG_NOT_ENOUGH_RAM_STR "Not enough RAM!"
#define MSG_SCANNING_3_STR "Scanning... %s\n"
#define MSG_DIRECTORY_TO_SCAN_STR "Directory to Scan..."
#define LABEL_NEWSSERVER_STR "Newsserver:"
#define LABEL_DEFAULT_STR "Default?:"
#define LABEL_POST_WITH_THIS_SERVER_STR "Post with this server?:"
#define MSG_LOGIN_STR "Login"
#define MSG_LOGIN_FAILED_STR "\033cLogin Failed!\nPlease try again with a correct login."
#define MSG_STARTUP_STR "Startup"
#define MSG_CONTINUE_OR_QUIT_STR "_Continue|Quit"
#define MSG_NEWS_DIRECTORY_DOES_NOT_EXIST_STR "\033cLogin Error!\nThe news directory for this login does not exist!\nYou may either quit and log in with a different username,\nor continue with the news directory set to 'PROGDIR:'"
#define MSG_PROGDIR_CANNOT_BE_ACCESSED_STR "\033cLogin Fatal Error!\nThe news directory 'PROGDIR:' could not be accessed!"
#define MSG_NEWS_DIRECTORY_CANNOT_BE_ACCESSED_STR "\033cLogin Error!\nThe news directory for this login could not be accessed!\nYou may either quit and log in with a different username,\nor continue with the news directory set to 'PROGDIR:'"
#define MSG_DEFAULT_FOLLOWUP_STR "On %d, %n wrote:"
#define MSG_DEFAULT_FROM_STR "Lazy Person"
#define MSG_CHARSET_ERROR_STR "Charset error!"
#define MSG_CONTINUE_STR "_Continue"
#define MSG_CHARSET_CANNOT_BE_ACCESSED_STR "\033cThe charset specified in your configuration\n(%s) could not be accessed!\nCurrent charset is set to iso-8859-1.\nYou should check charset setting in \"Write\" page of\nprogram settings window."
#define MSG_SHUTTING_DOWN_STR "Shutting Down.."
#define MSG_CLOSING_SOCKETS_STR "closing sockets.."
#define MSG_SAVING_PREFS_STR "saving preferences.."
#define MSG_SAVING_KILLFILE_STR "saving killfile.."
#define MSG_SAVING_SERVERS_STR "saving servers.."
#define MSG_FREEING_MEMORY_STR "freeing memory.."
#define MSG_DELETING_FILES_STR "deleting files.."
#define MSG_READING_GROUP_LIST_STR "Reading group list.."
#define MSG_READ_GROUPS_STR "Read %d Groups"
#define MSG_SORTING_LIST_STR "Sorting List.."
#define MSG_FOUND_GROUPS_2_STR "\033cFound %d Groups\n"
#define MSG_GROUP_MANAGER_STR "Group Manager"
#define MSG_GROUP_LIST_DOES_NOT_EXIST_STR "\033cThe file %s.gl does not exist!\nPlease select 'Fetch Group List' from\nthe Project Menu."
#define MSG_NEW_GROUP_FOR_SERVER_STR "Group Manager : New Groups for %s"
#define MSG_GROUP_MANAGER_2_STR "Group Manager : %s"
#define MSG_CANCEL_STR "Cancel"
#define MSG_MOVE_TO_WHICH_GROUP_STR "Move to which group?"
#define MSG_MOVE_STR "Move"
#define MSG_COPY_TO_WHICH_GROUP_STR "Copy to which group?"
#define MSG_MOVING_STR "Moving.."
#define MSG_COPYING_STR "Copying.."
#define MSG_MOVE_MESSAGE_STR "Move Message"
#define MSG_NO_MESSAGES_TO_MOVE_STR "\033cNo messages to move!"
#define MSG_COPY_MESSAGE_STR "Copy Message"
#define MSG_NO_MESSAGES_TO_COPY_STR "\033cNo messages to copy!"
#define MSG_DELETE_MESSAGES_STR "Delete Message(s)"
#define MSG_DELETE_OR_CANCEL_STR "_Delete|_Cancel"
#define MSG_DELETE_NOT_SENT_ARE_YOU_SURE_STR "\033cAre you sure you wish\nto Delete the selected Message(s)?\nWARNING - These messages have not been sent yet!"
#define MSG_DELETE_MESSAGES_ARE_YOU_SURE_STR "\033cAre you sure you wish\nto Delete the selected Message(s)?"
#define MSG_DELETING_STR "Deleting.."
#define MSG_DELETE_MESSAGE_STR "Delete Message"
#define MSG_NO_MESSAGES_TO_DELETE_STR "\033cNo messages to delete!"
#define MSG_UNDELETE_MESSAGES_STR "Undelete Message(s)"
#define MSG_UNDELETE_OR_CANCEL_STR "_Undelete|_Cancel"
#define MSG_UNDELETE_ARE_YOU_SURE_STR "\033cAre you sure you wish\nto Undelete the selected Message(s)?"
#define MSG_UNDELETING_STR "Undeleting.."
#define MSG_UNDELETE_MESSAGE_STR "Undelete Message"
#define MSG_NO_MESSAGES_TO_UNDELETE_STR "\033cNo messages to Undelete!"
#define MSG_MESSAGES_FROM_THIS_AUTHOR_STR "Messages from this Author"
#define MSG_RESPONSE_TO_MESSAGE_STR "Messages in Response to Message"
#define MSG_ALL_WHITH_THE_SAME_SUBJECT_STR "All Messages with the same Subject"
#define MSG_MESSAGES_FROM_SERVER_STR "All Messages from server %s"
#define MSG_MESSAGES_FROM_POSTING_HOST_STR "All Messages from NNTP posting host %s"
#define MSG_KILL_IN_ALL_GROUPS_STR "Kill in all Newsgroups"
#define MSG_KILL_IN_THIS_GROUP_STR "Kill in this Newsgroup"
#define MSG_EXPORT_ADDRESS_ARE_YOU_SURE_STR "Enter the following into YAM's address book?:\nName : %s\nEmail : %s"
#define MSG_EXPORT_ADDRESS_STR "Export Address"
#define MSG_YES_OR_CANCEL_STR "_Yes|_Cancel"
#define MSG_CANNOT_ACCESS_YAM_ADDRESSBOOK_STR "\033cCouldn't access file YAM:.addressbook"
#define MSG_ONLY_ONE_NEWSCOASTER_COPY_ALLOWED_STR "\033cYou may not open more than one copy of\nNewsCoaster at a time!"
#define MSG_NOT_AVAILABLE_STR "Not Available"
#define MSG_FUNCTION_NOT_AVAILABLE_WHEN_CONNECTED_STR "\033cThis function not available whilst\nNewsCoaster is connected with a newsserver!"
#define MSG_PLEASE_SELECT_GROUP_FOLDER_STR "\033cPlease select a newsgroup folder!"
#define MSG_DOWNLOAD_GROUP_LIST_ARE_YOU_SURE_STR "\033cAre you sure you wish to download\nthe Groups list for %s?\n(It may take some time)"
#define MSG_GET_GROUP_LIST_STR "Get Group List"
#define MSG_GROUP_LIST_DOWNLOADED_STR "\033c%d Groups found!\nGroup list has been downloaded into file \n%s.gl\nSelect Groups Manager from Program Settings to view list\n"
#define MSG_GROUP_LIST_STR "Group List"
#define MSG_SYSTEM_INFORMATION_STR "System Information"
#define MSG_SYSTEM_INFORMATION_SAVED_STR "\033cSystem Information saved to\nRAM:sysinfo.txt"
#define MSG_QUIT_PROGRAM_STR "Quit Program"
#define MSG_QUIT_OR_CANCEL_STR "_Quit|_Cancel"
#define MSG_QUIT_ARE_YOU_SURE_STR "\033cAre you sure you wish\nto Quit?"
#define MSG_SAVE_MESSAGE_STR "Save Message"
#define MSG_SAVE_DISCARD_OR_CANCEL_STR "_Save|_Discard|_Cancel"
#define MSG_SAVE_CHANGES_ARE_YOU_SURE_STR "\033cDo you wish to save the changes\nto this message?"
#define MSG_EDIT_NEWSGROUP_STR "Edit Newsgroup"
#define MSG_PLEASE_SELECT_GROUP_TO_EDIT_STR "\033cPlease select a newsgroup to edit!"
#define MSG_PLEASE_FINISH_EDITING_GROUP_STR "\033cPlease finish editing current group."
#define MSG_GROUP_ADVANCED_SETTINGS_STR "Newsgroup Advanced Settings"
#define MSG_PLEASE_SELECT_GROUP_STR "\033cPlease select a newsgroup!"
#define MSG_DELETE_GROUP_ARE_YOU_SURE_STR "\033cAre you *sure* you wish\nto Delete this Newsgroup?"
#define MSG_YOU_MAY_NOT_DELETE_FOLDER_STR "\033cYou may not delete this folder!"
#define MSG_ARCHIVE_GROUP_STR "Archive Newsgroup"
#define MSG_FILE_TO_SAVE_ARCHIVE_AS_STR "File to save archive as..."
#define MSG_SORT_NEWSGROUP_STR "Sort Newsgroup"
#define MSG_SORT_OR_CANCEL_STR "_Sort|_Cancel"
#define MSG_SORT_GROUP_ARE_YOU_SURE_STR "\033cAre you sure you wish to\nsort the newsgroups list alphabetically?\n(Current ordering will be lost!)"
#define MSG_RESET_ARTICLE_POINTER_STR "Reset Article Pointer"
#define MSG_RESET_OR_CANCEL_STR "_Reset|_Cancel"
#define MSG_RESET_ARTICLE_POINTER_ARE_YOU_SURE_STR "\033cReset the article pointer for this newsgroup\n - as if you had just created this newsgroup folder\n(see documentation for details)."
#define MSG_RESET_ARTICLE_POINTERS_STR "Reset Article Pointers"
#define MSG_RESET_ALL_POINTERS_ARE_YOU_SURE_STR "\033cReset the article pointer for all newsgroups\n - as if you had just created the newsgroup folders\n(see documentation for details)."
#define MSG_OPEN_GROUP_MANAGER_ARE_YOU_SURE_STR "\033cAre you sure you wish to open\nthe Group Manager window?\n(It takes a little time to read in\nall the groups)"
#define MSG_UPDATE_OR_CANCEL_STR "_Update|_Cancel"
#define MSG_UPDATE_GROUP_LIST_ARE_YOU_SURE_STR "\033cAre you sure you wish\nto Update the Newsgroup List?\n(Settings may be lost)"
#define MSG_UPDATE_GROUP_INDEX_ARE_YOU_SURE_STR "\033cAre you sure you wish\nto Update the index for this Group?\n"
#define MSG_UPDATE_INDICES_STR "Update Indices"
#define MSG_UPDATE_ALL_INDICES_ARE_YOU_SURE_STR "\033cAre you sure you wish\nto Update all the Group indices?\n(Will take a little time.)"
#define MSG_PLEASE_SELECT_MESSAGE_STR "\033cPlease select a message!"
#define MSG_EDIT_MESSAGE_STR "Edit Message"
#define MSG_MESSAGE_TO_EDIT_IS_SENT_STR "\033cNote that this message you are about to edit\nhas already been sent."
#define MSG_YOU_CAN_EDIT_ONLY_YOUR_MESSAGES_STR "\033cYou can only edit your own messages!\n(Those in 'Outgoing' or 'Sent')"
#define MSG_YOU_MUST_SELECT_MESSAGE_TO_EDIT_STR "\033cYou must first select a message to edit!"
#define MSG_SUPERSEDE_MESSAGE_STR "Supersede Message"
#define MSG_YOU_CAN_SUPERSEDE_ONLY_SENT_MESSAGES_STR "\033cYou can only supersede messages you have sent!"
#define MSG_YOU_MUST_SELECT_MESSAGE_TO_SUPERSEDE_STR "\033cYou must first select a message to supersede!"
#define MSG_CANCEL_MESSAGE_OR_NOT_STR "Cancel _Message|Don't Cancel"
#define MSG_CANCEL_MESSAGE_ARE_YOU_SURE_STR "\033cAre you sure you wish\nto Cancel this message?\n"
#define MSG_CANCEL_MESSAGE_QUEUED_STR "\033cCancel message placed in queue;\nSend News to cancel your message on the newsserver.\n"
#define MSG_IMMEDIATE_DELETE_ARE_YOU_SURE_STR "\033cAre you *sure* you wish\nto Delete the selected Message(s)?\nWARNING - These messages will be deleted immediately, and not\ncopied to the 'deleted folder'!"
#define MSG_DELETE_READ_MESSAGES_STR "Delete Read Messages"
#define MSG_IMMEDIATE_DELETE_READ_ARE_YOU_SURE_STR "\033cThis option will remove all read messages\nin this newsgroup.\nWARNING - These messages will be deleted immediately, and not\ncopied to the 'deleted folder'!"
#define MSG_DELETE_HEADERS_STR "Delete Headers"
#define MSG_REMOVE_HEADERS_ARE_YOU_SURE_STR "\033cThis option will remove all headers\nthat have not been entirely downloaded. "
#define MSG_DELETE_DUPLICATES_STR "Delete Duplicates"
#define MSG_DELETE_DUPLICATES_ARE_YOU_SURE_STR "\033cThis option will remove all duplicated messages\nin this folder. "
#define MSG_IMMEDIATE_DELETE_ALL_ARE_YOU_SURE_STR "\033cAre you *sure* you wish\nto Delete all the Messages in this folder?\nWARNING - These messages will be deleted immediately, and not\ncopied to the 'deleted folder'!"
#define MSG_IMMEDIATE_DELETE_ALL_GROUPS_ARE_YOU_SURE_STR "\033cAre you *sure* you wish\nto Delete ALL the Messages in ALL newsgroups?\n(This does not include outgoing or sent)\nWARNING - These messages will be deleted immediately, and not\ncopied to the 'deleted folder'!"
#define MSG_SURE_OR_CANCEL_STR "Yes I'm Sure|_Cancel"
#define MSG_DELETE_ALL_GROUPS_LAST_CHANCE_STR "\033cAre you absolutely sure you wish\nto Delete ALL the Messages in ALL newsgroups?\n(Last chance)\n(This does not include outgoing or sent)"
#define MSG_NEWSCOASTER_COMPOSING_MESSAGE_STR "NewsCoaster (composing message)"
#define MSG_VIEW_HEADERS_STR "View Headers"
#define MSG_KILL_MESSAGE_STR "Kill Message"
#define MSG_PLEASE_FINISH_DOWNLOADING_FIRST_STR "\033cPlease wait for downloading to finish first."
#define MSG_DOWNLOADING_MESSAGE_STR "Downloading Message"
#define MSG_CANNOT_DOWNLOAD_WHILE_DOWNLOADING_OTHER_MESSAGES_STR "\033cNewsCoaster cannot download articles whilst\nother messages are already being downloaded, sorry."
#define MSG_DOWNLOADING_BODIES_STR "Downloading bodies.."
#define MSG_DELETING_NOT_AVAILABLE_HEADERS_STR "Deleting no longer available headers..\n"
#define MSG_MARK_MESSAGE_STR "Mark Message"
#define MSG_ONLY_MESSAGES_IN_GROUPS_CAN_BE_MARKED_UNREAD_STR "\033cOnly messages in newsgroups can be marked as unread!"
#define MSG_ONLY_MESSAGES_IN_GROUPS_CAN_BE_MARKED_READ_STR "\033cOnly messages in newsgroups can be marked as read!"
#define MSG_ONLY_MESSAGES_IN_OUTGOING_CAN_BE_MARKED_HELD_STR "\033cOnly messages in outgoing can be marked as held!"
#define MSG_ONLY_MESSAGES_IN_OUTGOING_CAN_BE_MARKED_QUEUED_STR "\033cOnly messages in outgoing can be marked as queued!"
#define MSG_CHANGE_DATE_STR "Change Date"
#define MSG_YOU_CAN_CHANGE_DATE_OF_NOT_SENT_STR "\033cYou can only change the date of\nyour messages that have not been sent."
#define MSG_IMPOSSIBLE_TO_CHANGE_SETTINGS_WHEN_EDITING_MESSAGE_STR "\033cIt is not possible to change\nthe Program settings whilst editing a message.\nPlease finish editing current message"
#define MSG_DELETE_USER_STR "Delete User"
#define MSG_UNABLE_TO_DELETE_CURRENT_USER_STR "\033cYou may not delete the current login!\nIf you wish to delete yourself, please login under a new user, and\nthen delete this user."
#define MSG_DELETE_USER_ARE_YOU_SURE_STR "\033cAre you *sure* you wish\nto delete this User?\n"
#define MSG_YES_OR_NO_STR "Yes|No"
#define MSG_USER_DELETED_DELETE_PREFS_STR "The database entry for this user has been deleted.\nDo you now wish to delete all their prefs?"
#define MSG_NEW_USER_STR "New User"
#define MSG_USER_NAME_TOO_SHORT_STR "\033cUser name must be at least 3 characters.\nPlease enter a longer user name."
#define MSG_USER_NAME_EXISTS_STR "\033cThis user name already exists.\nPlease enter another one."
#define MSG_NEWS_DIRECTORY_IN_USE_STR "\033cThis news directory is being used by another user.\nPlease select somewhere else."
#define MSG_PASSWORD_TOO_SHORT_STR "\033cPassword must be at least 4 characters.\nPlease enter a longer password, or untick the password."
#define MSG_CANNOT_CREATE_FOLDER_STR "\033cError! Couldn't create folder:\n%s"
#define MSG_ENTER_NEW_PASSWORD_STR "Please enter a new password,\nor press cancel to leave it unchanged."
#define MSG_CHANGE_PASSWORD_STR "Change Password"
#define MSG_ERROR_3_STR "Error"
#define MSG_CANNOT_CREATE_FOLDER_2_STR "\033cCannot create Folder!"
#define MSG_RESET_OR_NOT_STR "_Reset|_Don't Reset"
#define MSG_SERVER_CHANGED_RESET_ARTICLE_POINTER_STR "\033cYou have changed the NNTP server for this group, do you wish to reset the article pointer?\n(see documentation for details - if unsure, you should Reset)."
#define MSG_JOINED_MESSAGE_STR "Joined Message"
#define MSG_YOU_MUST_ENTER_EMAIL_ADDRESS_STR "\033cYou must enter an email\naddress in the form:\n  user@domain\n"
#define MSG_BAD_LINE_LENGTH_STR "\033cA line length of %d is\nconsidered bad style;\nyou are advised to change to a value\nbetween 60 and 80!"
#define MSG_ADD_SERVER_STR "Add Server"
#define MSG_PLEASE_FINISH_EDITING_SERVER_BEFORE_ADDING_NEW_STR "Please finish adding/editing the current server\nbefore adding a new one."
#define MSG_EDIT_SERVER_STR "Edit Server"
#define MSG_PLEASE_FINISH_EDITING_SERVER_BEFORE_EDITING_NEW_STR "Please finish adding/editing the current server\nbefore editing a new one."
#define MSG_DEFAULT_SERVER_CHANGED_RESET_ALL_POINTERS_STR "\033cYou have changed the default NNTP server, do you wish to reset the article pointer\nfor all groups using the default server?\n(see documentation for details - if unsure, you should Reset)."
#define MSG_DELETE_SERVER_STR "Delete Server"
#define MSG_DELETE_SERVER_ARE_YOU_SURE_STR "\033cAre you sure you wish\nto delete this server entry?"
#define MSG_SERVER_DELETED_RESET_ARTICLE_POINTERS_STR "\033cDo you wish to reset article pointers for any groups\nthat were using this server?\n(see documentation for details - if unsure, you should Reset)."
#define MSG_CANNOT_DELETE_SERVER_BEING_EDITED_STR "You cannot delete a server that is being edited!"
#define MSG_CANNOT_DELETE_LAST_SERVER_STR "You cannot delete the last remaining server!"
#define MSG_SERVER_ADDRESS_CHANGED_RESET_POINTERS_STR "\033cYou have changed this server's address.\nDo you wish to reset article pointers for any groups\nthat were using this server?\n(see documentation for details - if unsure, you should Reset)."
#define MSG_SELECT_FILE_TO_READ_STR "Select File to Read in"
#define MSG_DELETE_KILL_ENTRY_STR "Delete Killfile Entry"
#define MSG_DELETE_KILL_ENTRY_ARE_YOU_SURE_STR "\033cAre you sure you wish\nto delete this killfile entry?"
#define MSG_SAVE_KILLFILE_STR "Save Killfile"
#define MSG_GROUP_NOT_FOUND_STR "\033cGroup not found!"
#define MSG_SEARCH_GROUPS_STR "Search Groups"
#define MSG_PLEASE_SELECT_SOME_GROUPS_STR "\033cPlease select some groups."
#define MSG_SEARCHING_STR "Searching.."
#define MSG_SEARCHING_2_STR "Searching: %s"
#define MSG_STATISTICS_STR "Statistics"
#define MSG_UNKNOWN_STR "Unknown"
#define MSG_CLIPBOARD_EMPTY_STR "\033cThe clipboard is empty."
#define MSG_NO_TEXT_IN_CLIP_STR "\033cThe clipboard does not contain text."
#define MSG_NO_AREA_MARKED_STR "\033cNo area marked."
#define MSG_NOTHING_TO_REDO_STR "\033cNothing to redo."
#define MSG_NOTHING_TO_UNDO_STR "\033cNothing to undo."
#define MSG_NO_MEMORY_FOR_UNDO_STR "There is not enough memory\nto keep the undo buffer.\n\nThe undobuffer is lost."
#define MSG_NO_BOOKMARK_INSTALLED_STR "There is no bookmark installed!"
#define MSG_BOOKMARK_LOST_STR "Your bookmark has unfortunately been lost."
#define MSG_GROUP_STR "\033bGroup"
#define MSG_MSGS_STR "\033bMsgs"
#define MSG_SUB_STR "\033bSub"
#define MSG_ONLINE_STR "\033bOnline"
#define MSG_SUBJECT_BOLD_STR "\033bSubject"
#define MSG_DATE_STR "\033bDate"
#define MSG_NEWSGROUPS_BOLD_STR "\033bNewsgroups"
#define MSG_FROM_BOLD_STR "\033bFrom"
#define MSG_SIZE_STR "\033bSize"
#define MSG_LINES_STR "\033bLines"
#define MSG_VALUE_STR "\033bValue"
#define MSG_FREQUENCY_STR "\033bFrequency"
#define MSG_NAME_STR "\033bName"
#define MSG_NEWS_DIRECTORY_STR "\033bNews Directory"
#define MSG_PASSWORD_PROTECTED_STR "\033bPassword Protected?"
#define MSG_SUPERVISOR_STR "\033bSupervisor?"
#define MSG_FILENAME_STR "\033bFilename"
#define MSG_MIME_TYPE_STR "\033bMIME Type"
#define MSG_VIEWER_STR "\033bViewer"
#define MSG_INDEFINATELY_STR "Indefinately"
#define MSG_DAYS_SINCE_CREATION_STR "%d days since Creation"
#define MSG_DAYS_SINCE_LAST_USED_STR "%d days since Last Used"
#define MSG_DOES_NOT_CONTAIN_2_STR "Doesn't Contain"
#define MSG_UNKOWN_2_STR "Unknown???"
#define MSG_HEADER_BOLD_STR "\033bHeader"
#define MSG_TEXT_STR "\033bText"
#define MSG_GROUPS_STR "\033bGroups"
#define MSG_MATCH_STR "\033bMatch"
#define MSG_ACTION_STR "\033bAction"
#define MSG_SKIP_REST_STR "\033bSkip Rest?"
#define MSG_CREATION_STR "\033bCreation"
#define MSG_LAST_USED_STR "\033bLast Used"
#define MSG_TIME_LIMIT_STR "\033bTime Limit"
#define MSG_Y_STR "Y"
#define MSG_N_STR "N"
#define MSG_SERVER_BOLD_STR "\033bServer"
#define MSG_PORT_STR "\033bPort"
#define MSG_USERNAME_STR "\033bUsername"
#define MSG_AUTHENCICATION_STR "\033bAuthentication"
#define MSG_DEFAULT_STR "\033bDefault"
#define MSG_POSTING_STR "\033bPosting"
#define MSG_IMPORTING_FOLDER_STR "Importing Folder.."
#define MSG_SEE_GUIDE_FOR_MORE_INFO_STR "Please see the AmigaGuide documentation for more information."
#define MSG_AUTHORS_STR "%s %s"
#define MSG_FAILED_TO_CREATE_EDITOR_MCC_STR "Failed to create Text Editor Custom Class."
#define MSG_ABOUTTEXT_STR "\033c\033bNewsCoaster\033n\n(v%s)\n%s"
#define MSG_NEWSREADER_STR "Newsreader"
#define MSG_NEW_NEWSGROUP_STR "New Newsgroup"
#define LABEL_NEWSGROUP_NAME_STR "Newsgroup Name:"
#define LABEL_DESCRIPTION_STR "Description:"
#define LABEL_DEFAULT_SIG_STR "Default .sig:"
#define LABEL_SUBSCRIBE_STR "Subscribe?"
#define MSG_CANCEL_2_STR "C_ancel"
#define MSG_LAST_DOWNLOAD_DATE_STR "Last Download Date:"
#define MSG_FOLDER_LOCATION_STR "Folder Location:"
#define MSG_APPROVED_HEADER_STR "'Approved' Header?:"
#define MSG_ALTERNATIVE_NAME_STR "Alternative Name?:"
#define MSG_ALTERNATIVE_EMAIL_STR "Alternative Email?:"
#define MSG_JOIN_MESSAGES_STR "Join Messages"
#define LABEL_SUBJECT_STR "Subject:"
#define MSG_JOIN_STR "_Join"
#define LABEL_YOUR_NAME_STR "Your Name"
#define LABEL_EMAIL_FOR_POSTING_STR "Email for Posting"
#define LABEL_REAL_EMAIL_FOR_POSTING_STR "Real Email for Emailing"
#define LABEL_ORGANISATION_STR "Organisation"
#define LABEL_TIME_ZONE_STR "Time Zone:"
#define LABEL_DATE_DISPLAY_FORMAT_STR "Date Display Format:"
#define LABEL_ADD_DST_ADJUSTMENT_STR "Add Adjustment for DST?:"
#define LABEL_USE_LOCALE_PREFS_STR "Use Locale Prefs?:"
#define LABEL_ALWAYS_CHECK_FOR_DUPES_STR "Always Check for Duplicates?:"
#define LABEL_DELETE_HEADER_IF_NO_BODY_STR "Delete Header if Body Not Avail.?:"
#define LABEL_DONT_SHOW_FROM_SUBJ_WHEN_DL_STR "Don't Show From/Subject When d/l?:"
#define LABEL_SWITCH_GROUPS_WHEN_DL_STR "Switch Groups When d/l?:"
#define LABEL_DONT_CONFIRM_WHEN_DELETING_STR "Don't Confirm When Deleting?:"
#define LABEL_ALWAYS_CONFIRM_ON_QUIT_STR "Always Confirm on Quit?:"
#define LABEL_LOGGING_ENABLED_STR "Logging Enabled?:"
#define LABEL_DELETE_LOG_ON_STARTUP_STR "Delete Log on Startup?:"
#define MSG_NEW_SERVER_STR "_New Server"
#define MSG_EDIT_SERVER_2_STR "_Edit Server"
#define MSG_MAKE_DEFAULT_STR "Make De_fault"
#define MSG_USE_FOR_POSTING_STR "Use for _Posting"
#define MSG_DELETE_SERVER_2_STR "_Delete Server"
#define MSG_GET_GROUPS_STR "Get Groups"
#define MSG_GROUPS_MANAGER_STR "Groups Manager"
#define LABEL_SMTP_SERVER_STR "SMTP (Mail) Server"
#define LABEL_FOLLOWUP_ATTRIBUTATION_LINE_STR "Followup Attributation Line:"
#define LABEL_CHARSET_STR "Charset:"
#define MSG_READ_FROM_FILE_STR "_Read From File"
#define LABEL_LINE_LENGTH_STR "Line Length:"
#define LABEL_AUTO_REWRAP_STR "Auto. Rewrap"
#define LABEL_USE_X_NO_ARCHIVE_STR "Use 'X-No-Archive' Header?"
#define LABEL_USE_SHORT_X_NEWSREADER_STR "Use Shortened X-Newsreader Header:"
#define LABEL_SNIP_SIG_STR "Snip .sig?"
#define LABEL_MULTIPLE_VIEW_WINDOWS_STR "Multiple View Windows?"
#define LABEL_2ND_LEVEL_QUOTING_STR "2nd Level Quoting"
#define MSG_2ND_LEVEL_QUOTE_STR "2nd Level Quoted Text"
#define LABEL_COLOURED_STR "Coloured"
#define MSG_COLOURED_TEXT_STR "Coloured Text"
#define LABEL_FLAGS_STR "Flags"
#define LABEL_DATE_STR "Date"
#define LABEL_FROM_NEWSGROUP_STR "From/Newsgroup"
#define LABEL_SIZE_STR "Size"
#define LABEL_N_OF_LINES_STR "# of Lines"
#define LABEL_MIME_TYPE_STR "MIME _Type"
#define LABEL_VIEWER_STR "_Viewer"
#define MSG_PLEASE_SELECT_VIEWER_STR "Please Select a Viewer"
#define LABEL_DEFAULT_VIEWER_STR "De_fault Viewer"
#define MSG_NEW_STR "_New"
#define MSG_SERVER_STR "Server"
#define LABEL_NNTP_SERVER_STR "NNTP (News) Server"
#define LABEL_PORT_STR "Port"
#define LABEL_USE_NNTP_AUTH_STR "Use NNTP-Auth?"
#define LABEL_USER_STR "User"
#define LABEL_PASSWORD_STR "Password"
#define LABEL_KILLFILE_SETTINGS_STR "KillFile Settings"
#define LABEL_IF_HEADER_STR "If the Header:"
#define LABEL_IN_THE_GROUPS_STR "in the Newsgroups:"
#define LABEL_THEN_STR "then.."
#define LABEL_SKIP_REST_STR "Skip Rest?"
#define MSG_ADD_REPLACE_STR "_Add/Replace"
#define MSG_DUPLICATE_STR "Du_plicate"
#define LABEL_ADVERT_KILLFILE_STR "'Advert' KillFile?"
#define LABEL_FIND_STR "Find:"
#define MSG_SUBSCRIBE_STR "_Subscribe"
#define MSG_DOWLOAD_GROUP_LIST_STR "_Download Group List"
#define LABEL_SEARCH_IN_STR "Search in:"
#define LABEL_SEARCH_FOR_STR "Search for:"
#define LABEL_CASE_SENSITIVE_STR "Case-sensitive?:"
#define MSG_START_SEARCH_STR "Start Search"
#define LABEL_TYPE_STR "Type:"
#define MSG_START_STR "Start"
#define MSG_SAVE_STR "_Save"
#define MSG_DISPLAY_STR "_Display"
#define MSG_CREATE_NEW_USER_DESCRIPTION_STR "Create New User - see the 'Users'\nsection in the documentation for more\ndetails. If you are running NewsCoaster\nfor the first time, you must set up a\nuser for yourself. Please see the\n'Configuration' section in the\ndocumentation for more details."
#define LABEL_USER_NAME_STR "User Name:"
#define LABEL_PASSWORD_2_STR "Password:"
#define LABEL_NEWS_DIRECTORY_STR "News Directory:"
#define MSG_SELECT_DIRECTORY_TO_STORE_NEWS_STR "Please Select a Directory to Store News.."
#define LABEL_SUPERVISOR_STR "Supervisor?"
#define LABEL_USE_PASSWORD_STR "Use Password?"
#define MSG_COPY_PREFS_STR "Copy Prefs?"
#define MSG_USERS_STR "Users"
#define MSG_ADD_NEW_USER_STR "_Add New User"
#define MSG_DELETE_USER_2_STR "_Delete User"
#define MSG_USER_LOGIN_STR "User Login"
#define MSG_PLEASE_ENTER_NEW_PASSWORD_STR "Please enter a new password,\nor press cancel to leave it unchanged."
#define MSG_ABOUT_STR "About..."
#define MSG_FAILED_TO_CREATE_APPLICATION_STR "Failed to create Application."
#define MSG_CREATE_GROUP_HELP_STR "Create the new Newsgroup for\nyou to subscribe to"
#define MSG_CANCEL_CREATE_GROUP_HELP_STR "Close this window and do not\ncreate a new Newsgroup"
#define MSG_GROUP_NAME_HELP_STR "Usenet Name of the Newsgroup you\nwish to subscribe to (eg,\ncomp.sys.amiga.misc)"
#define MSG_GROUP_DESCRIPTION_HELP_STR "Description of the Newsgroup\n(eg, Amiga Programming) -\nOptional"
#define MSG_DEFAULT_SIGNATURE_HELP_STR "If you are using signatures,\nthen this one will be the\ndefault for postings to the\nnewsgroup (see menu\n'Preferences/Program Settings')"
#define MSG_MAXIMUM_MESSAGES_TO_DOWNLOAD_HELP_STR "You can limit the maximum\nnumber of messages to\ndownload each time you fetch\nnew news. If Unlimited, all\nnews since the last download\ndate will be downloaded."
#define MSG_MAXIMUM_LINES_TO_DOWNLOAD_HELP_STR "You can choose not to\ndownload messages that are\nlonger than a certain number\nof lines. Alternatively, you\ncan choose to have no such\nlimit."
#define MSG_OFFLINE_VIEWING_HELP_STR "Offline viewing downloads\nentire messages for you to\nread when offline. Online\nviewing only downloads the\nheaders; the rest of the\nmessage is downloaded when\nyou go to read it (thus you\nmust be online for this)."
#define MSG_ONLY_SUBSCRIBED_GROUPS_WILL_BE_DOWNLOADED_HELP_STR "Only news from currently\nsubscribed to Newsgroups\nwill be downloaded when\nfetching news."
#define MSG_UPDATE_GROUP_HELP_STR "Update the parameters for\nthis Newsgroup"
#define MSG_CANCEL_UPDATE_GROUP_HELP_STR "Cancel these changes and\nrevert to the previous\nsettings for this Newsgroup"
#define MSG_GROUP_NAME_TO_SUBSCRIBE_HELP_STR "Name of the Newsgroup you\nwish to subscribe to (eg,\ncomp.sys.amiga.misc)"
#define MSG_LAST_DOWNLOAD_HELP_STR "The date and (local) time\nyou last downloaded for this\nnewsgroup (or the creation\ndate if you haven't yet\ndownloaded)"
#define MSG_KEEP_CHANGES_HELP_STR "Keep these changes"
#define MSG_CANCEL_CHANGES_HELP_STR "Cancel these changes and\nrevert to the previous\nsettings"
#define MSG_YOUR_NAME_HELP_STR "Your name (which will appear\nin messages that you post)"
#define MSG_YOUR_EMAIL_HELP_STR "Your email address, to be used\nwhen posting news - does not\nhave to be correct, see\ndocumentation for details"
#define MSG_YOUR_REAL_EMAIL_HELP_STR "Your real email address, to be\nused when sending email. Must\nbe correct"
#define MSG_ORGANISATION_HELP_STR "Your organisation (company,\nuniversity, whatever you\nwant). Can be left blank"
#define MSG_SERVER_ADDRESS_HELP_STR "The address of your\nnewsserver (see\ndocumentation for a list of\npublic ones)"
#define MSG_PORT_HELP_STR "The port to use to connect to\nthis newsserver (will usually\nbe 119)"
#define MSG_POSTING_SERVER_HELP_STR "The address of your\nnewsserver that you wish to\nuse for posting. Leave blank\nif you wish to use the same\nserver that you read from\n(above)"
#define MSG_SMTP_SERVER_HELP_STR "The address of your SMTP\nmail server (used to send\nemail)"
#define MSG_SMTP_DOMAIN_HELP_STR "Your domain for your SMTP\nmail server"
#define MSG_FOLLOWUP_TEXT_HELP_STR "The text to be displayed when\nyou follow-up a news item.\nCodes:\n  %n - Insert Recipient's Name\n  %d - Insert Date/Time\n  %g - Insert Newsgroup\n  %m - Insert MessageID"
#define MSG_SELECT_CHARSET_HELP_STR "Select a charset convertor"
#define MSG_SET_TIME_ZONE_HELP_STR "Set the Time-Zone that you\nlive in (so that your\nmessages appear in the right\norder in the newsgroups)"
#define MSG_USE_LOCALE_HELP_STR "If this is ticked, then\nNewsCoaster will read the\ntimezone from your Locale\nPreferences"
#define MSG_DST_HELP_STR "Tick this box for Daylight\nSaving Time - one hour ahead"
#define MSG_DATE_FORMAT_HELP_STR "How you wish dates to be\ndisplayed in the messages\nlist. You MUST select\n'Update All Indices' from\nthe Newsgroups menu for this\nto take effect"
#define MSG_WRITE_LOG_HELP_STR "Ticking this box means that\nNewsCoaster's activity will\nbe written to the text file\n'.log' in the NewsCoaster\nfolder"
#define MSG_DELETE_LOG_HELP_STR "Delete the logfile everytime\nNewsCoaster starts (logfiles\ncan get rather large\notherwise)"
#define MSG_SWITCH_GROUP_HELP_STR "Ticking this box means that\nwhen downloading news,\nNewsCoaster will switch the\ncurrent folder to the\nnewsgroup you are downloading\nfor"
#define MSG_MODE_HELP_STR "When downloading in online\nmode, only the headers will be\ndownloaded when you fetch\nnews; the message body is\ndownloaded when you go to view\nthe message. Sometimes the\nmessage body may no longer be\navailable (especially if some\ntime has passed) - in such\ncases, the header will be\nautomatically\ndeleted if this option is\nticked."
#define MSG_CONFIRM_QUIT_HELP_STR "If this is unticked,\nNewsCoaster will quit\nimmediately when asked to\nclosed instead of asking you\nto confirm (unless you are\nwriting a message)"
#define MSG_SHOW_FROM_HELP_STR "If this box is ticked,\nNewsCoaster won't show the\nFrom and Subject line of\nmessages as it downloads them"
#define MSG_CONFIRM_DELETE_HELP_STR "When you delete files, you\nwon't be asked for\nconfirmation if this box is\nticked. This does not apply to\n'permenant' deleting."
#define MSG_DUPE_CHECK_HELP_STR "Normally NewsCoaster will only\ncheck for duplicates when it\nconsiders necessary, though\nsometimes duplicate messages\nmay repeatedly appear on a\nnewsserver's list. Checking\nthis option will ensure no\nduplicate messages are\ndownloaded, but it makes\ndownloading slower."
#define MSG_X_NO_ARCHIVE_HELP_STR "Inserting the X-No-Archive\nheader means your message\nwill not be stored in news\narchives such as\ngroups.google.com"
#define MSG_SHORT_X_NEWSREADER_HELP_STR "Tick this box to have a\nshort X-Newsreader header"
#define MSG_SELECT_SIGNATURE_HELP_STR "Select a signature to modify"
#define MSG_GET_SIGNATURE_FROM_FILE_HELP_STR "Insert a signature from a\nfile"
#define MSG_TYPE_SIGNATURE_HERE_HELP_STR "Type your signature here"
#define MSG_LINE_LENGTH_HELP_STR "Set the linelength when\nwriting messages"
#define MSG_AUTO_REWRAP_HELP_STR "Automatically rewrap the\ntext before quoting, on\nreplies·(avoids overspilling\nlines)"
#define MSG_STRIP_SIGNATURE_HELP_STR "Automatically strip the\nsignature of messages before\nreplying"
#define MSG_DISPLAY_FLAGS_HELP_STR "Display the Flags column in\nthe message list window"
#define MSG_DISPLAY_FROM_HELP_STR "Display the From or Newsgroup\ncolumn in the message list\nwindow"
#define MSG_DISPLAY_DATE_HELP_STR "Display the Date column in the\nmessage list window"
#define MSG_DISPLAY_SUBJECT_HELP_STR "Display the Subject column in\nthe message list window"
#define MSG_DISPLAY_SIZE_HELP_STR "Display the Size column in the\nmessage list window"
#define MSG_DISPLAY_LINES_STR "Display the Number Of Lines\ncolumn in the message list\nwindow"
#define MSG_ADD_KILFILE_HELP_STR "Add this killfile to the\nlist"
#define MSG_NEW_KILLFILE_HELP_STR "Create a new killfile"
#define MSG_DELETE_KILLFILE_HELP_STR "Delete the selected killfile"
#define MSG_DUPLICATE_KILLFILE_HELP_STR "Duplicate the selected\nkillfile"
#define MSG_KILL_HEADER_HELP_STR "The header you wish to kill\non (exact match, case\ninsensitive - includes the\ncolon). eg, 'From:'\nAlternatively, leave empty\nto kill on any header"
#define MSG_KILL_TEXT_HELP_STR "If the header contains this\ntext, then the message will\nnot be downloaded (substring\nsearch, case insensitive).\neg, '@hotmail.com'"
#define MSG_KILL_GROUP_HELP_STR "The newsgroups to apply this\nkillfile to (substring\nsearch, case insensitive -\nleave blank for all\nnewsgroups). eg. '',\n'comp.sys.amiga.',\n'alt.dreams.lucid'"
#define MSG_KILLFILE_EXPIRE_HELP_STR "You may set the killfile to\neither never expire, to\nexpire so many days after it\nwas created, or to expire so\nmany days after the killfile\nwas last used"
#define MSG_DAYS_LAST_FOR_HELP_STR "The number of days to last\nfor (either after creation,\nor since last used, as\nspecified by the cycle\ngadget)"
#define MSG_WHAT_TO_DO_IF_MATCHED_HELP_STR "What to do if the text is\nmatched."
#define MSG_SORT_OF_MATCH_HELP_STR "What sort of match are we\nafter."
#define MSG_WHAT_TO_DO_IF_KILLFILE_MATCHED_HELP_STR "What to do if the killfile is\nmatched."
#define MSG_CHECK_REST_HELP_STR "If this killfile is matched,\nshould we carry on checking\nagainst the rest of the\nkillfiles?"
#define MSG_ADVERT_KILLFILE_STR "If this killfile is enable,\nNewsCoaster will see if the\nlast word in the subject\nline is a number, since this\nusually indicates an advert\nor other spam - see docs for\nmore details"
#define MSG_OPEN_NEW_VIEW_WINDOW_HELP_STR "When you read a new message,\ndo you want a new View window\nto open, or use an existing\none?"
#define MSG_SELECT_MIME_TYPE_HELP_STR "Select the MIME Type that\nyou wish to set a viewer\nprogram for"
#define MSG_SELECT_VIEWER_HELP_STR "Select the external program\nyou wish you use to view\nthis MIME Type, along with\nthe arguments - enter %s for\nthe filename"
#define MSG_SELECT_DEFAULT_VIEWER_HELP_STR "Select the external program\nyou wish you use for files\nthat don't match any of the\nabove listed MIME Types, along\nwith the arguments - enter %s\nfor the filename"
#define MSG_CREATE_NEW_MIME_TYPE_HELP_STR "Create a new MIME Type"
#define MSG_DELETE_MIME_TYPE_HELP_STR "Delete the entry for the\ncurrently selected MIME Type"
#define MSG_NEW_FOLDER_HELP_STR "Set up a new folder so that\nyou can subscribe to this\nnewsgroup"
#define MSG_DOWNLOAD_GROUP_LIST_HELP_STR "Download the newsgroup list\nfrom your newsserver"
#define MSG_SEARCH_GROUP_HELP_STR "Enter in some text and press\nenter, and the next\nnewsgroup containing that\ntext will be found"
#define MSG_SEARCH_HEADER_HELP_STR "The header you wish to\nsearch in"
#define MSG_SEARCH_STRING_HELP_STR "The string you wish to\nsearch for (substring\nsearch)"
#define MSG_CASE_SENSITIVE_SEARCH_HELP_STR "Whether the search is to be\ncase-sensitive or not"
#define MSG_STATISTICS_CRITERIA_HELP_STR "What you wish to categorise\nthe frequency count by\n(Note: 'X-Newsreader' is\nslower than the others)"
#define MSG_ADD_THIS_USER_HELP_STR "Add this new user"
#define MSG_DO_NOT_ADD_USER_STR "Do not add this new user"
#define MSG_USERNAME_HELP_STR "Username - must be between 3\nand 8 characters, and unique"
#define MSG_PASSWORD_HELP_STR "Password - must be between 4\nand 8 characters. The user\ncan change it later if he\nwishes. Don't forget your\npassword!"
#define MSG_PASSWORD_PROTECTION_HELP_STR "Whether you want password\nprotection enabled or not"
#define MSG_NEWS_DIRECTORY_HELP_STR "Where on your hard disk you\nwish to store the news\nmessages for this user. Must\nbe unique. If the drawer\ndoes not exist, it will be\ncreated."
#define MSG_SUPERVISOR_HELP_STR "Whether this user is to be a\nsupervisor. Only supervisors\ncan delete users, and add\nnew users."
#define MSG_COPY_PREFS_HELP_STR "If this is ticked, the\npreferences (but NOT\nnewsgroup list, .sigs or\nkillfiles) of the current\nuser will be copied to the\nnew user"
#define MSG_ADD_USER_HELP_STR "Add a new user"
#define MSG_DELETE_USER_HELP_STR "Delete this user!"
#define MSG_ENTER_USERNAME_HELP_STR "Please enter your username"
#define MSG_ENTER_PASSWORD_HELP_STR "Please enter your password,\nif required. If your login\nis not password protected,\nthen you can leave this\nblank."
#define MSG_NEW_PASSWORD_HELP_STR "Your new password - must be\nbetween 4 and 8 characters.\nDon't forget your new\npassword!"
#define MSG_CHANGE_PASSWORD_HELP_STR "Change your password settings"
#define MSG_CANCEL_CHANGES_2_HELP_STR "Cancel these changes"
#define MSG_COUNT_DIFFERS_FROM_ENTRIES_STR "count %d differs from entries %d !"
#define MSG_CANNOT_ALLOCATE_FIB_STR "Cannot allocate fib - exfile()"
#define MSG_WARNING_STR "Warning"
#define MSG_OLD_PREFS_FILE_STR "Your current '.prefs' file appears to be from a previous version!\nIf you encounter problems, reset your Account settings ('Preferences/Program Settings') and select 'Newsgroups/Update Groups'"
#define MSG_ABORT_STR "_Abort"
#define MSG_EMAIL_FORMAT_STR "EMail Format"
#define MSG_PLAIN_TEXT_STR "Plain Text"
#define MSG_ATACHMENT_CORRUPTED_STR "\033cThe attachment \"%s\" is corrupted!"
#define MSG_YDECODED_ATTACH_STR "Ydecoded Attachment"
#define MSG_FOLLOWUP_REPLY_STR "Followup/Reply"
#define MSG_FOLLOWUP_REPLY_OR_CANCEL_STR "_Followup|_Reply via Email|_Cancel"
#define MSG_FOLLOWUP_OR_REPLY_STR "\033cDo you wish to followup to the message on the newsgroup,\nor reply to the author via email?"
#define MSG_FIND_STR "Find"
#define MSG_NO_MORE_OCCURANCES_STR "No More Occurances Found"
#define MSG_NO_OCCURANCES_FOUND_STR "No Occurances Found"
#define MSG_HEADERS_STR "Headers"
#define MSG_PLAIN_TEXT_SECTION_STR "Plain text section"
#define MSG_HTML_SECTION_STR "HTML section"
#define MSG_SAVE_NEWS_ITEM_AS_STR "Save News Item As..."
#define MSG_ENCODING_STR "\033bEncoding"
#define MSG_LENGTH_STR "\033bLength"
#define MENU_MESSAGE_STR "Message"
#define MENU_FOLLOWUP_REPLY_STR "Followup/Reply..."
#define MENU_EXPORT_STR "Export..."
#define MENU_ADD_TO_KILLFILE_2_STR "Add to Killfile..."
#define MENU_EXPORT_ADDRESS_2_STR "Export Address to YAM"
#define MENU_MARK_AS_2_STR "Mark as"
#define MENU_NORMAL_2_STR "Normal"
#define MENU_IMPORTANT_2_STR "Important"
#define MENU_TOGGLE_HEADERS_STR "Toggle All/Standard Headers"
#define MENU_PREVIOUS_IN_THREAD_STR "Previous in Thread"
#define MENU_PREVIOUS_STR "Previous"
#define MENU_NEXT_STR "Next"
#define MENU_DELETE_THEN_NEXT_STR "Delete then Next"
#define MENU_CLOSE_WINDOS_STR "Close Window"
#define MENU_EDIT_STR "Edit"
#define MENU_FIND_IN_MESSAGE_STR "Find in Message..."
#define MENU_FIND_NEXT_STR "Find Next"
#define MSG_COPY_STR "Copy"
#define MENU_ROT13_DECODE_STR "Rot13 Decode"
#define MENU_ATTACHMENTS_STR "Attachments"
#define MENU_VIEW_ATTACHMENT_STR "View Attachment"
#define MENU_SAVE_ATTACHMENT_STR "Save Attachment..."
#define MSG_VIEW_STR "View"
#define MSG_ATTACHMENTS_LIST_HELP_STR "Attachments list"
#define MSG_VIEW_ATTACHMENT_HELP_STR "View the selected message part\nor attachment."
#define MSG_SAVE_ATTACHMENT_HELP_STR "Save the selected message part\nor attachment."
#define MSG_FOLLOWUP_REPLY_2_STR "_Followup/Reply"
#define MSG_ADD_TO_KILLFILE_STR "Add to _Killfile"
#define MSG_PREVIOUS_MESSAGE_STR "_Previous Message"
#define MSG_PREVIOUS_IN_THREAD_STR "Previous in _Thread"
#define MSG_DELETE_NEXT_STR "_Delete/Next"
#define MSG_NEXT_MESSAGE_STR "_Next Message"
#define MSG_FIND_TEXT_STR "Find Text"
#define LABEL_FIND_2_STR "Find.."
#define LABEL_CASE_SENSITIVE_2_STR "Case Sensitive?"
#define MSG_FIND_2_STR "_Find"
#define MSG_ADD_TO_KILLFILE_HELP_STR "Make a new killfile entry,\nrelated to this message (you\ncan choose from various\noptions)"
#define MSG_PREVIOUS_HELP_STR "View the previous message in\nthis Newsgroup"
#define MSG_PREVIOUS_IN_THREAD_HELP_STR "View the message previous in\nthis thread, ie, the message\nwhich this message is replying\nto. If this button disables\nwhen you click it, it means\nthis is a new message, or the\nprevious message was either\nnot downloaded, deleted or\ndownloaded with a version\nprevious to v1.24"
#define MSG_DELETE_NEXT_HELP_STR "Delete this message, and\nthen view the next message\nin this Newsgroup"
#define MSG_NEXT_HELP_STR "View the next message in\nthis Newsgroup"
#define MSG_FOLLOWUP_REPLY_HELP_STR "Followup or reply to this\nmessage"
#define MSG_EXPORT_HELP_STR "Save or Display parts or all\nof this message"
#define MSG_EMAIL_STYLE_HELP_STR "EMail means colours will be\nused for quoted\ntext ('>') and '*','/','-'\nwill be converted to bold,\nitalics and underlined\nrespectively. Plain text\njust displays without\nconversion"
#define MSG_TEXT_TO_SEARCH_HELP_STR "Enter the text you wish to\nsearch for in this message."
#define MSG_FIND_NEXT_HELP_STR "Find the next occurance of the\ntext in this message."
#define MSG_EXPORT_STR "Export"
#define MSG_VIEW_PART_STR "_View Part"
#define MSG_SAVE_PART_STR "_Save Part"
#define MSG_VIEW_UUE_STR "View UUEncoded"
#define MSG_SAVE_UUE_STR "Save UUEncoded"
#define MSG_MESSAGE_STR "Message"
#define MSG_ATTACHMENTS_STR "Attachments"
#define MSG_OPTIONS_STR "Options"
#define MSG_PLEASE_SELECT_NEWSGROUP_STR "Please Select a Newsgroup"
#define MSG_ADD_REMOVE_GROUP_STR "Add/Remove Newsgroup"
#define MSG_DISCARD_OR_CANCEL_STR "_Discard|_Cancel"
#define MSG_DISCARD_CHANGES_ARE_YOU_SURE_STR "\033cAre you sure you wish\nto discard all changes to this message\n(since last saved)?"
#define MSG_SELECT_FILE_TO_ATTACH_STR "Please Select File to Attach"
#define LABEL_NEWSGROUPS_STR "Newsgroups:"
#define LABEL_TO_STR "To:"
#define MSG_ADD_ATTACHMENT_STR "_Add Attachment"
#define MSG_DELETE_ATTACHMENT_STR "_Delete Attachment"
#define LABEL_FROM_STR "From:"
#define LABEL_FOLLOWUP_TO_STR "Followup-To:"
#define MSG_SEND_TO_QUEUE_STR "Send to _Queue"
#define MSG_POSTPONE_STR "P_ostpone"
#define MSG_ROT13_STR "_Rot13"
#define MSG_READ_FROM_FILE_2_STR "Read From _File"
#define MSG_SEND_HELP_STR "Send your message\nimmediately (you must be\nonline) and copy the message\nto the Sent folder"
#define MSG_ADD_OR_REMOVE_GROUP_TO_POST_HELP_STR "Add or remove a newsgroup to\npost to by selecting from\nthe list"
#define MSG_ADD_OR_REMOVE_GROUP_TO_FOLLOWUP_TO_HELP_STR "Add or remove a newsgroup to\nfollowup-to to by selecting\nfrom the list"
#define MSG_QUEUE_HELP_STR "Copy the message to the\nOutgoing folder, to be\nposted later when you are\nonline by selecting the menu\noption 'Project/Send News'"
#define MSG_HOLD_HELP_STR "Copy the message to the\nOutgoing folder, but do not\nsend at all (you must\nre-edit it first)"
#define MSG_CANCEL_MESSAGE_HELP_STR "Cancel this message (or\ncancel the changes to it if\nthis is an edited\nmessage)"
#define MSG_INSERT_TEXT_FROM_FILE_HELP_STR "Insert text read in from a\nfile"
#define MSG_SELECT_SIGNATURE_FOR_MESSAGE_HELP_STR "Select the .sig you wish to\nuse for this message"
#define MSG_TO_HELP_STR "If you wish to email the\nmessage to anyone, place\ntheir email address here.\nMultiple emails must be\nseparated with a comma"
#define MSG_NEWSGROUP_HELP_STR "The Newsgroup you wish to\npost to. Multiple Newsgroups\nmust be separated with a\ncomma"
#define MSG_SUBJECT_HELP_STR "The subject of your message"
#define MSG_FROM_HELP_STR "What you wish to appear in\nthe 'From:' header"
#define MSG_FOLLOWUP_TO_HELP_STR "Followups to your message\nwill only go to the\nnewsgroups specified here,\nor they will go to the same\nnewsgroups listed in the\nNewsgroups field, if this\nfield is left blank"
#define MSG_WRITE_MESSAGE_STR "Write Message"
#define MSG_EDIT_OR_CONTINUE_STR "_Edit|_Continue"
#define MSG_NO_SUBJECT_STR "You have not specifed a subject for your message.\nDo you wish to edit the message?"
#define MSG_EMPTY_MESSAGE_STR "The message body is empty.\nDo you wish to edit the message?"
#define MSG_ALL_QUOTED_STR "The message seems to consists entirely of quoted text.\nDo you wish to edit the message?"
#define MSG_NO_RAM_FOR_ATTACHMENTS_STR "Not enough RAM for attachments!"
#define MSG_CANNOT_FIND_FILE_TO_ATTACH_STR "\033cCannot find file to attach:\n%s"
#define MSG_NEWSCOASTER_EDITING_MESSAGE_STR "NewsCoaster (editing message)"
#define MSG_NO_RAM_TO_READ_MESSAGE_STR "Not enough RAM to read message!\n"
#define MSG_OLD_MESSAGE_STR "Old Message!"
#define MSG_REPLYING_TO_AN_OLD_POST_STR "\033cI am just warning you that you are replying\nto a rather old post!"
#define MSG_FOLLOWUP_OR_REPLY_2_STR "_Followup to Newsgroup|_Reply via email"
#define MSG_EMAIL_REPLY_REQUESTED_STR "\033cThe author requested that he be replied to via email.\nIt may be better to do so."
#define MSG_YOU_MUST_SELECT_MESSAGE_TO_REPLY_STR "\033cYou must first select a message to followup/reply to!"
#define MENU_MESSAGE_2_STR "Message"
#define MSG_SAVE_2_STR "Save"
#define MSG_RECV_FAILED_EBADF_STR "Failed to receive any data ( EBADF )"
#define MSG_RECV_FAILED_ENOTCONN_STR "Failed to receive any data ( ENOTCONN )"
#define MSG_RECV_FAILED_EWOULDBLOCK_STR "Failed to receive any data ( EWOULDBLOCK )"
#define MSG_RECV_FAILED_EINTR_STR "Failed to receive any data ( EINTR )"
#define MSG_RECV_FAILED_UNKNOWN_STR "Failed to receive any data ( %d )"
#define MSG_POSTER_STR "poster"
#define LABEL_SUBJECT_2_STR "Subject"
#define MSG_DUPLICATING_FILE_STR "Duplicating File"
#define MSG_RENAME_OVERWRITE_OR_CANCEL_STR "*_Rename|_Overwrite|Cancel"
#define MSG_FILE_ALREADY_EXISTS_STR "File already exists"

#endif /* CATCOMP_STRINGS */


/****************************************************************************/


struct LocaleInfo
{
    APTR li_LocaleBase;
    APTR li_Catalog;
};



#endif /* NEWSCOASTER_CATALOG_H */
